import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AccountUnavailable } from "@/components/account-unavailable";
import { createAnswerAction } from "@/features/behavioral/actions";
import { AnswerForm } from "@/features/behavioral/answer-form";
import { isAccountPlatformAvailable } from "@/lib/account-platform";
import { requireMemberProfile } from "@/lib/auth/guards";
import { getBehavioralWorkspaceData } from "@/lib/behavioral/queries";
export const metadata: Metadata = { title: "Draft behavioral answer", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function NewBehavioralAnswerPage({ params, searchParams }: { params: Promise<{ questionId: string }>; searchParams: Promise<{ application?: string; company?: string; story?: string }> }) { if (!isAccountPlatformAvailable()) return <AccountUnavailable />; const { questionId } = await params; const query = await searchParams; await requireMemberProfile(`/behavioral/questions/${questionId}/answers/new`); const data = await getBehavioralWorkspaceData(); const question = data.questions.find((item) => item.id === questionId); if (!question) notFound(); const application = data.applications.find((item) => item.id === query.application); if (!data.stories.length) return <div className="behavioral-workspace"><div className="page-width behavioral-form-width"><header className="tracker-form-page-header"><h1>Start with a story</h1><p>Answer variants frame a saved story; they do not create a second source of facts for this question.</p></header><p className="behavioral-empty-inline">Create a reusable factual story first, then return here to tailor its presentation.</p><Link className="button button-sm" href="/behavioral/stories/new">Create source story</Link></div></div>; return <div className="behavioral-workspace"><div className="page-width behavioral-form-width"><header className="tracker-form-page-header"><h1>Create answer variant</h1><p>{question.prompt}{application ? ` · ${application.company_name} — ${application.role_title}` : ""}</p></header><AnswerForm action={createAnswerAction.bind(null, question.id)} questionId={question.id} stories={data.stories.map(({ id, title, situation, task, action, result, reflection, short_summary }) => ({ id, title, situation, task, action, result, reflection, short_summary }))} applications={data.applications.map(({ id, company_name, company_slug, role_title }) => ({ id, company_name, company_slug, role_title }))} defaultCompany={application?.company_slug ?? query.company ?? question.companySlug} defaultApplication={application?.id} defaultStory={query.story} /></div></div>; }
