import Link from "next/link";
import { MermaidDiagram } from "@/components/mermaid-diagram";
import { CommonMistakes, InterviewFollowUps, TradeoffTable, WorkedExample } from "@/components/system-design-article";
import { LessonCallout, LessonHeading } from "@/components/system-design-lesson";
import { ConceptFirst, TechnologyLessonEnd } from "./shared";

const zookeeperArchitecture = `flowchart TD
  C1[Scheduler client] --> E[ZooKeeper ensemble]
  C2[Worker client] --> E
  C3[Service client] --> E
  E --> Z1["/services/api/instance-1 · ephemeral"]
  E --> Z2["/election/candidate-0002 · sequential"]
  E --> Z3["/config/current · persistent"]
  Z1 -. watch event .-> C3`;
const etcdArchitecture = `flowchart LR
  C[Controllers and clients] --> L[etcd leader]
  L --> F1[Raft follower]
  L --> F2[Raft follower]
  L --> K[(Versioned key-value state)]
  K --> W[Watch streams]
  K --> X[Lease-bound keys]`;
const flinkArchitecture = `flowchart LR
  K[Kafka or another source] --> F[Flink operators]
  F --> S[(Keyed state)]
  S --> F
  F --> D[Derived stream / DB / search / alerts]
  F -. checkpoint .-> O[(Durable checkpoint storage)]`;

export function ZooKeeperTechnologyLessonContent() { return <>
  <ConceptFirst need="a small strongly coordinated place for membership, configuration, and leader-election metadata" technology="Apache ZooKeeper" />
  <LessonHeading level={2} id="problem">Coordination metadata is different from application data</LessonHeading><p>Schedulers, partition managers, and service registries sometimes need participants to agree on current membership or authority. ZooKeeper provides a hierarchical namespace of small znodes, sessions, watches, and ordering primitives. It is not a general database for profiles, orders, or large payloads.</p>
  <LessonHeading level={2} id="model">Znodes, sessions, ephemeral state, and watches</LessonHeading><MermaidDiagram chart={zookeeperArchitecture} title="Clients coordinate through a small hierarchical namespace" description="Scheduler, worker, and service clients use a ZooKeeper ensemble containing persistent configuration, an ephemeral service registration, and an election candidate node; clients observe relevant watch events." /><p>Persistent znodes remain until changed or deleted. Ephemeral znodes are tied to a client session and can represent live membership. Standard watches are one-time triggers; clients re-read state and re-establish observation rather than treating a notification as a complete event log.</p>
  <LessonHeading level={2} id="patterns">Build patterns from recipes, not timing assumptions</LessonHeading><TradeoffTable><table><thead><tr><th>Pattern</th><th>Primitive intuition</th><th>Failure question</th></tr></thead><tbody><tr><td>Membership</td><td>Ephemeral registration</td><td>What happens during disconnection or session expiration?</td></tr><tr><td>Leader election</td><td>Ordered contender nodes and one selected owner</td><td>How is stale leadership fenced?</td></tr><tr><td>Configuration</td><td>Persistent metadata plus watch/re-read</td><td>Can clients safely run with old configuration?</td></tr></tbody></table></TradeoffTable>
  <LessonHeading level={2} id="failure">An ensemble requires quorum to coordinate</LessonHeading><p>ZooKeeper replicates its ordered state across an ensemble and needs a quorum for progress. A client that loses its session must behave conservatively: an old process may no longer own an ephemeral registration or leadership position. Cross-link <Link href="/system-design/patterns/leases-and-fencing-tokens">leases and fencing</Link>; a notification alone does not revoke external side effects.</p>
  <CommonMistakes><ul><li>Storing large or high-volume application data in ZooKeeper.</li><li>Treating one-shot watches as a durable stream of every change.</li><li>Assuming a disconnected client still owns leadership.</li><li>Implementing election recipes without handling session expiration and stale actors.</li><li>Explaining Zab internals when the interview asks why coordination storage exists.</li></ul></CommonMistakes>
  <InterviewFollowUps><ul><li>What metadata truly requires strong coordination?</li><li>What happens when the client disconnects?</li><li>How does a new leader prevent an old leader from writing?</li><li>Can the system degrade without the ensemble?</li><li>Why not use an application database?</li></ul></InterviewFollowUps>
  <TechnologyLessonEnd id="zookeeper" practice={["job-scheduler", "distributed-queue", "kafka-platform"]}>ZooKeeper coordinates small metadata through znodes, sessions, ephemeral state, and watches. Explain quorum, session loss, re-reading state, and fencing stale leaders.</TechnologyLessonEnd>
</>; }

export function EtcdTechnologyLessonContent() { return <>
  <ConceptFirst need="strongly ordered key-value metadata with watches, leases, and compare-and-swap" technology="etcd" />
  <LessonHeading level={2} id="problem">A versioned key-value control-plane store</LessonHeading><p>etcd fits configuration, membership, leader election, and controller metadata that needs strong ordering and observation. Kubernetes is a concrete association, but the interview lesson is the control-plane problem: small important state whose updates participants must agree on.</p>
  <LessonHeading level={2} id="architecture">Raft-backed agreement exposes revisions to clients</LessonHeading><MermaidDiagram chart={etcdArchitecture} title="Raft-replicated metadata with watches and leases" description="Controllers send requests through an etcd leader replicated to two followers. The versioned key-value state feeds watch streams and may bind keys to expiring leases." /><p>The keyspace is flat and versioned by revisions. Watches stream changes from revisions while history is available. Transactions provide atomic compare/then/else operations, useful for compare-and-swap and higher-level coordination.</p>
  <LessonHeading level={2} id="leases">Leases represent liveness, not timeless ownership</LessonHeading><p>A lease has a TTL and is refreshed with keep-alives; attached keys are removed when it expires or is revoked. A paused or partitioned client can mistakenly believe it still owns work after the cluster expires its lease. Use a monotonically newer fencing token or validate authority at the protected resource.</p><LessonCallout variant="important" title="A lock API is not the entire correctness proof"><p>State the failure model, lease expiration, external side effects, and fencing. Mutual exclusion inside etcd does not automatically stop a stale process from writing to another database.</p></LessonCallout>
  <LessonHeading level={2} id="comparison">etcd vs ZooKeeper</LessonHeading><TradeoffTable><table><thead><tr><th>Dimension</th><th>etcd</th><th>ZooKeeper</th></tr></thead><tbody><tr><td>Data model</td><td>Flat versioned key-value space</td><td>Hierarchical znode namespace</td></tr><tr><td>Observation</td><td>Revision-based watch streams</td><td>Standard one-shot watches plus persistent variants</td></tr><tr><td>Liveness</td><td>Lease-bound keys</td><td>Session-bound ephemeral znodes</td></tr><tr><td>Consensus family</td><td>Raft</td><td>ZooKeeper Atomic Broadcast</td></tr><tr><td>Ecosystem example</td><td>Kubernetes control-plane state</td><td>Distributed-system coordination recipes and legacy ecosystems</td></tr></tbody></table></TradeoffTable><p>Neither is a universal winner. Generic interviews value why coordination stores exist more than product API recall.</p>
  <CommonMistakes><ul><li>Using etcd for large, rapidly changing user datasets.</li><li>Assuming watch consumers never fall behind or cross compaction boundaries.</li><li>Equating a lease with permanent external ownership.</li><li>Saying Raft means the service is always available.</li><li>Name-dropping Kubernetes without describing the metadata requirement.</li></ul></CommonMistakes>
  <InterviewFollowUps><ul><li>Which keys need linearizable coordination?</li><li>How does a watcher recover after disconnection?</li><li>What happens when the cluster loses quorum?</li><li>How are stale lease holders fenced?</li><li>Why not ZooKeeper or a transactional database?</li></ul></InterviewFollowUps>
  <TechnologyLessonEnd id="etcd" practice={["job-scheduler", "key-value-store", "distributed-cache"]}>etcd is a Raft-backed, versioned key-value store for control-plane metadata. Explain revisions, watches, compare-and-swap, lease expiry, quorum, and fencing stale actors.</TechnologyLessonEnd>
</>; }

export function FlinkTechnologyLessonContent() { return <>
  <ConceptFirst need="stateful event-time computation over continuous streams" technology="Apache Flink" />
  <LessonHeading level={2} id="problem">Kafka transports history; Flink computes over it</LessonHeading><p>A simple consumer can parse events and write results. Flink becomes compelling when computation holds state across events, reasons about when events occurred, evaluates windows, and restores distributed processing state after failure. Kafka is a common source, not a mandatory partner.</p>
  <LessonHeading level={2} id="architecture">Sources, stateful operators, sinks, and checkpoints</LessonHeading><MermaidDiagram chart={flinkArchitecture} title="Stateful stream-processing pipeline" description="An event source feeds Flink operators that read and update keyed state, emit to downstream systems, and periodically store checkpoints in durable storage." /><p>Keyed state places all events for one logical key on the appropriate operator instance. Checkpoints capture sufficient operator state and source positions to resume after failure. End-to-end guarantees still depend on the source, sink connector, and side-effect protocol.</p>
  <LessonHeading level={2} id="time">Event time corrects arrival-time distortion</LessonHeading><WorkedExample title="A delayed purchase"><pre><code>{`event occurred:  12:00:01
event arrived:   12:00:20

Processing-time logic may place it in the wrong window.
Event-time logic uses the occurrence timestamp and lateness policy.`}</code></pre><p>A watermark estimates how far event time has progressed so operators can produce results despite out-of-order arrivals. It does not prove that no earlier event will arrive. Define allowed lateness and what happens to late events.</p></WorkedExample>
  <LessonHeading level={2} id="windows">Windows bound continuous computation</LessonHeading><TradeoffTable><table><thead><tr><th>Window</th><th>Mental model</th><th>Example</th></tr></thead><tbody><tr><td>Tumbling</td><td>Fixed, non-overlapping buckets</td><td>Purchases per store every five minutes</td></tr><tr><td>Sliding</td><td>Overlapping windows evaluated repeatedly</td><td>Error rate over the last ten minutes each minute</td></tr><tr><td>Session</td><td>Activity grouped until an inactivity gap</td><td>User browsing session</td></tr></tbody></table></TradeoffTable>
  <LessonHeading level={2} id="recovery">Checkpoints restore computation, not arbitrary external reality</LessonHeading><p>On failure, Flink can restore operator state and source positions from a consistent checkpoint and replay input. A sink must participate with appropriate transactional or idempotent semantics for an end-to-end claim. A call to an external payment API remains an application correctness boundary.</p>
  <LessonHeading level={2} id="fit">Flink vs a simple consumer</LessonHeading><TradeoffTable><table><thead><tr><th>Simple consumer may be enough</th><th>Flink becomes more compelling</th></tr></thead><tbody><tr><td>Stateless mapping or validation</td><td>Large keyed state across events</td></tr><tr><td>Straightforward idempotent database writes</td><td>Event-time windows and late-data policy</td></tr><tr><td>Small volume and simple recovery</td><td>Distributed checkpointed computation</td></tr><tr><td>Ordinary request/background logic</td><td>Continuous fraud, metrics, ETL, enrichment, sessionization</td></tr></tbody></table></TradeoffTable>
  <CommonMistakes><ul><li>Adding Flink because Kafka is present.</li><li>Using processing time when product semantics require event time.</li><li>Claiming a watermark proves completeness.</li><li>Claiming checkpoints make arbitrary external effects exactly once.</li><li>Choosing Flink for a stateless low-volume consumer.</li></ul></CommonMistakes>
  <InterviewFollowUps><ul><li>What state must survive across events?</li><li>Which timestamp defines the product result?</li><li>How late can data arrive and what happens then?</li><li>How are checkpointed source positions coordinated with the sink?</li><li>Why is a normal consumer insufficient?</li></ul></InterviewFollowUps>
  <LessonHeading level={2} id="selection-matrix">Technology selection reference</LessonHeading><LessonCallout variant="tradeoff" title="Options, not automatic selections"><p>This table identifies technologies worth considering. Every choice still needs requirements, failure behavior, consistency, cost, and a simpler-alternative check.</p></LessonCallout><TradeoffTable><table><thead><tr><th>Need</th><th>Technology worth considering</th></tr></thead><tbody><tr><td>Shared in-memory cache or typed transient state</td><td>Redis</td></tr><tr><td>Retained event stream and replay</td><td>Kafka</td></tr><tr><td>Relational transactions</td><td>PostgreSQL</td></tr><tr><td>Managed key-oriented distributed store</td><td>DynamoDB</td></tr><tr><td>Distributed full-text search</td><td>Elasticsearch / OpenSearch</td></tr><tr><td>Large object bytes</td><td>S3 / object storage</td></tr><tr><td>Distributed wide-column data</td><td>Cassandra</td></tr><tr><td>Flexible broker routing</td><td>RabbitMQ</td></tr><tr><td>Managed AWS work queue</td><td>SQS</td></tr><tr><td>Distributed coordination metadata</td><td>ZooKeeper / etcd</td></tr><tr><td>Stateful event-time stream computation</td><td>Flink</td></tr></tbody></table></TradeoffTable>
  <TechnologyLessonEnd id="flink-deep-dive" practice={["event-analytics", "metrics-platform", "kafka-platform"]}>Flink is for stateful event-time computation. Defend keyed state, windows, watermarks, late data, checkpoints, sink correctness, and why a simple consumer is insufficient.</TechnologyLessonEnd>
</>; }
