import Link from "next/link";
import { ConsumerGroupDemo } from "@/components/consumer-group-demo";
import { MermaidDiagram } from "@/components/mermaid-diagram";
import { CommonMistakes, FailureDeepDive, InterviewFollowUps, TradeoffTable, WorkedExample } from "@/components/system-design-article";
import { LessonCallout, LessonHeading } from "@/components/system-design-lesson";
import { ConceptFirst, TechnologyLessonEnd } from "./shared";

const redisArchitecture = `flowchart TD
  A[Application servers] --> R[(Redis cluster)]
  A --> D[(Durable database)]
  R --> P[Primary shard]
  P --> X[Replica]
  P --> Y[Replica]
  R -. miss / recovery .-> D`;
const kafkaArchitecture = `flowchart TD
  P[Producers] --> B[Kafka brokers]
  B --> P0[Topic partition 0]
  B --> P1[Topic partition 1]
  B --> P2[Topic partition 2]
  P0 --> G1[Consumer group A]
  P1 --> G1
  P2 --> G1
  P0 --> G2[Consumer group B]
  P1 --> G2
  P2 --> G2`;
const kafkaReplication = `flowchart LR
  W[Producer write] --> L[Partition leader]
  L --> R1[Follower replica]
  L --> R2[Follower replica]
  L --> C[Consumers read retained log]`;
const postgresArchitecture = `flowchart LR
  A[Application] --> P[(PostgreSQL primary)]
  P -->|WAL stream| R1[(Read standby)]
  P -->|WAL stream| R2[(Read standby)]
  A -->|staleness-tolerant reads| R1
  A -->|correctness-sensitive work| P`;

export function RedisTechnologyLessonContent() { return <>
  <ConceptFirst need="shared low-latency state with an explicit durability and failure contract" technology="Redis" />
  <LessonHeading level={2} id="problem">What problem does Redis solve?</LessonHeading><p>Your application repeatedly serves small objects, increments shared counters, ranks scores, or coordinates temporary state across many servers. Reading the durable database for every operation wastes capacity. Redis places typed, memory-oriented shared state on a shorter path—but the interview is about what happens when that state is stale, full, partitioned, or unavailable.</p>
  <LessonHeading level={2} id="mental-model">Mental model and core architecture</LessonHeading><MermaidDiagram chart={redisArchitecture} title="Shared low-latency state with an explicit durable boundary" description="Application servers use a Redis cluster for shared fast state and a durable database where the workload requires an authoritative source. A Redis primary shard replicates to replicas." /><p>Redis can sit in front of a database as a cache or serve counters, sessions, ranking, rate-limit state, coordination, and some stream/queue workloads. Those uses do not share one durability requirement.</p>
  <LessonHeading level={2} id="structures">Choose a structure from the access pattern</LessonHeading><TradeoffTable><table><thead><tr><th>Structure</th><th>Interview use</th><th>Question to ask</th></tr></thead><tbody><tr><td>String</td><td>Cached object, session, counter</td><td>Is the value bounded and independently replaceable?</td></tr><tr><td>Hash</td><td>Fields for one logical object</td><td>Do fields change independently?</td></tr><tr><td>List</td><td>Simple ordered ends or queue-like work</td><td>Do I actually need acknowledgement or replay semantics?</td></tr><tr><td>Set</td><td>Membership and set operations</td><td>Is exact membership required?</td></tr><tr><td>Sorted set</td><td>Leaderboard and score ordering</td><td>What scope and time window define rank?</td></tr><tr><td>Stream</td><td>Retained append-oriented events</td><td>Would a dedicated streaming platform better fit retention and operations?</td></tr></tbody></table></TradeoffTable>
  <LessonHeading level={2} id="ttl-eviction">TTL, expiration, and eviction are separate decisions</LessonHeading><p><code>user:42 → TTL 300 seconds</code> can bound a cache, session, rate-limit window, or temporary record. Expiration is not a promise that every key disappears at the exact wall-clock instant. Cross-link <Link href="/system-design/fundamentals/ttl-and-expiration">TTL</Link>; then separately decide what Redis should do at its configured memory limit.</p><TradeoffTable><table><thead><tr><th>Policy family</th><th>Meaning</th></tr></thead><tbody><tr><td>LRU-oriented</td><td>Prefer removing less recently used candidates.</td></tr><tr><td>LFU-oriented</td><td>Prefer removing less frequently used candidates.</td></tr><tr><td>TTL-oriented</td><td>Prefer keys with expiration characteristics.</td></tr><tr><td>No eviction</td><td>Reject memory-growing writes instead of silently choosing victims.</td></tr></tbody></table></TradeoffTable><p>The exact Redis policy must match whether losing a value means a harmless miss, a degraded feature, or broken correctness. Review the canonical <Link href="/system-design/fundamentals/eviction-policies">eviction</Link> lesson first.</p>
  <LessonHeading level={2} id="persistence-replication">Persistence and replication do not create one universal durability guarantee</LessonHeading><p>Redis can use point-in-time RDB snapshots, append-only AOF logging, both, or no persistence. Recovery point and latency depend on configuration. Replication is normally asynchronous, so an acknowledged primary write may not yet exist on a replica when failure occurs. Persistence and replicas improve recovery options; neither automatically makes Redis the correct primary store for every workload.</p><FailureDeepDive failure="The Redis tier is unavailable or has just failed over." impact="Cache misses or transient-state reads surge toward downstream systems; some recent state may be absent depending on replication and persistence choices." detection="Track errors, latency, memory pressure, evictions, replication health, and downstream load." mitigation="Use bounded timeouts, request coalescing, admission control, gradual warming, replicas where appropriate, and a deliberate degraded mode." tradeoff="Falling back to the database preserves features only while that database can absorb the traffic." />
  <LessonHeading level={2} id="cluster-hot-keys">Cluster scaling partitions keys, not request popularity</LessonHeading><p>Redis Cluster assigns keys to a fixed set of hash slots that nodes own; it is not generic consistent hashing. Moving slots changes ownership as the cluster changes. A cluster expands aggregate memory and throughput, but a celebrity key at 200,000 RPS still concentrates on its owner even when ordinary keys average 100 RPS.</p><WorkedExample title="A hot key survives even distribution"><pre><code>{`ordinary key   = 100 RPS
celebrity key  = 200,000 RPS

Even key counts across shards ≠ even request load.`}</code></pre><p>Consider application-local caching, read distribution where the topology supports it, explicit replicated copies, or <Link href="/system-design/fundamentals/cache-stampede-thundering-herd">request coalescing</Link>. Validate correctness and invalidation for every copy.</p></WorkedExample>
  <LessonHeading level={2} id="choose">When to choose it—and when not to</LessonHeading><TradeoffTable><table><thead><tr><th>Choose Redis when</th><th>Do not add Redis merely when</th></tr></thead><tbody><tr><td>A shared cache removes meaningful repeated work.</td><td>The primary database already meets latency and load requirements.</td></tr><tr><td>Atomic counters, TTL state, membership, or ranking fit native structures.</td><td>You need arbitrary relational queries or unbounded large values.</td></tr><tr><td>The failure and durability contract is explicit.</td><td>“Memory is fast” is the only justification.</td></tr></tbody></table></TradeoffTable><p>Compared with Memcached, Redis offers richer structures plus persistence, replication, and broader coordination options; Memcached offers a simpler distributed-memory-cache model. Choose from workload and operational needs, not unsupported benchmark folklore.</p>
  <CommonMistakes><ul><li>Calling Redis only a cache—or automatically a database replacement.</li><li>Claiming it never persists or always persists safely.</li><li>Assuming Cluster solves hot keys.</li><li>Assuming database fallback can absorb a total cache outage.</li><li>Treating a simple lock acquisition as correct under every pause, partition, and lease-expiry case.</li><li>Ignoring key/value size and finite memory.</li></ul></CommonMistakes>
  <InterviewFollowUps><ul><li>What happens when Redis is unavailable?</li><li>What receives a TTL, and how was that duration chosen?</li><li>How do you scale beyond one node and handle a hot key?</li><li>Would Redis own the primary user record?</li><li>How is the database protected during recovery?</li></ul></InterviewFollowUps>
  <TechnologyLessonEnd id="redis" practice={["url-shortener", "rate-limiter", "leaderboard", "news-feed"]}>Redis is shared low-latency state for caches, counters, ranking, sessions, and coordination. Explain memory limits, TTL and eviction, persistence, slot-based partitioning, replication lag, hot keys, and disappearance.</TechnologyLessonEnd>
</>; }

export function KafkaTechnologyLessonContent() { return <>
  <ConceptFirst need="a retained partitioned event stream with replay and independent consumer progress" technology="Apache Kafka" />
  <LessonHeading level={2} id="problem">Why Kafka instead of a normal work queue?</LessonHeading><p>Kafka retains an ordered sequence of records per partition. Consumers track their own offsets; one group advancing does not globally delete a record for every other group. That model fits event history, replay, CDC distribution, and multiple derived consumers better than a queue whose primary abstraction is pending work.</p>
  <LessonHeading level={2} id="architecture">Core architecture</LessonHeading><MermaidDiagram chart={kafkaArchitecture} title="Retained partitions serving independent consumer groups" description="Producers write to a Kafka broker cluster containing three topic partitions. Two independent consumer groups each track their own progress across those partitions." /><p>A cluster contains brokers. Topics split into partitions. Each partition has an ordered log, leader, replicas, and offsets. Producers choose partitions directly or through keys; consumers in a group divide assigned partitions.</p><MermaidDiagram chart={kafkaReplication} title="Partition leader and replicas" description="A producer writes to a partition leader, which replicates records to followers before consumers read the retained log according to configuration." />
  <LessonHeading level={2} id="partition-groups">Keys determine ordering and parallelism</LessonHeading><p><code>partition_key = customer_id</code> can keep one customer&apos;s events in one partition, preserving partition-scoped order. It can also make a celebrity customer hot. With eight partitions, one consumer group normally cannot use more than eight active consumers for that topic&apos;s partition work at once, subject to assignment and topology.</p><ConsumerGroupDemo /><p>Cross-link <Link href="/system-design/fundamentals/partitions-and-partition-keys">partition keys</Link>, <Link href="/system-design/fundamentals/consumer-groups">consumer groups</Link>, and <Link href="/system-design/fundamentals/ordering-guarantees">ordering</Link>; Kafka implements those concepts rather than replacing them.</p>
  <LessonHeading level={2} id="replay">Offsets, retention, replay, and compaction</LessonHeading><pre><code>{`Database → CDC → Kafka
                  ├→ Search indexer
                  ├→ Analytics
                  └→ Warehouse loader`}</code></pre><p>Each consumer can resume or replay within retained history. Retention can be policy-driven by time or size. Log compaction is a distinct keyed policy that preserves at least the latest value for keys according to Kafka&apos;s compaction semantics; it does not mean “keep every historical record forever.”</p>
  <LessonHeading level={2} id="durability">Replication and exactly-once nuance</LessonHeading><p>Each partition&apos;s leader replicates to followers. Producer acknowledgements, replication factor, in-sync replica state, and broker failure determine durability; avoid an absolute “Kafka never loses data.” Idempotent producers and Kafka transactions can coordinate records and offsets for supported Kafka processing boundaries.</p><LessonCallout variant="important" title="External effects remain external"><p><code>Kafka → payment API</code> is not made globally exactly once by a Kafka setting. The application still needs an idempotency key, durable outcome, reconciliation, or another correctness protocol at that side-effect boundary.</p></LessonCallout>
  <LessonHeading level={2} id="operations">Operational interview concerns</LessonHeading><TradeoffTable><table><thead><tr><th>Concern</th><th>Design consequence</th></tr></thead><tbody><tr><td>Partition count</td><td>Bounds group parallelism and influences metadata, files, and reassignment work.</td></tr><tr><td>Consumer lag</td><td>Measures distance from current history and recovery time pressure.</td></tr><tr><td>Hot partition</td><td>A skewed key can overload one leader and its consumers.</td></tr><tr><td>Rebalancing</td><td>Ownership moves; consumers must handle pauses and safe offset progress.</td></tr><tr><td>Large messages</td><td>Pressure network, memory, storage, and processing; objects may belong elsewhere.</td></tr><tr><td>Schema evolution</td><td>Independent producers and consumers need compatible contracts.</td></tr></tbody></table></TradeoffTable>
  <LessonHeading level={2} id="alternatives">Kafka vs queue-oriented systems</LessonHeading><TradeoffTable><table><thead><tr><th>Requirement</th><th>Kafka tendency</th><th>Queue tendency</th></tr></thead><tbody><tr><td>Retained history and replay</td><td>Central capability</td><td>Often not central</td></tr><tr><td>Independent consumer groups</td><td>Natural offset ownership</td><td>Separate queues/subscriptions may be needed</td></tr><tr><td>Simple background job dispatch</td><td>Often more machinery than required</td><td>Natural fit</td></tr><tr><td>Delayed jobs and straightforward retries</td><td>Application patterns required</td><td>Often first-class operational model</td></tr></tbody></table></TradeoffTable>
  <CommonMistakes><ul><li>Saying Kafka guarantees exactly once for arbitrary external effects.</li><li>Claiming ordering across an entire multi-partition topic.</li><li>Adding Kafka for one simple background worker.</li><li>Ignoring lag, retention, rebalances, hot keys, and schema changes.</li><li>Calling partitions only a scaling detail when they also define ordering.</li></ul></CommonMistakes>
  <InterviewFollowUps><ul><li>Why is replay a requirement?</li><li>Which key defines order and can it become hot?</li><li>How are offsets committed relative to side effects?</li><li>What happens during broker failure or group rebalancing?</li><li>Could a managed queue satisfy the simpler requirement?</li></ul></InterviewFollowUps>
  <TechnologyLessonEnd id="kafka-deep-dive" practice={["metrics-platform", "notification-service", "event-analytics", "kafka-platform"]}>Kafka is a retained, partitioned event log whose consumers own offsets. Defend the partition key, retention, replay, replication acknowledgement, lag, and external-side-effect boundary.</TechnologyLessonEnd>
</>; }

export function PostgreSqlTechnologyLessonContent() { return <>
  <ConceptFirst need="relational integrity and transactions across related records" technology="PostgreSQL" />
  <LessonHeading level={2} id="problem">A strong default when relationships and correctness matter</LessonHeading><p>Payments, reservations, accounts, and commerce often change related records together. PostgreSQL offers tables, constraints, joins, indexes, and transactions in one coherent model. Start here when access patterns may evolve and correctness matters; do not flee to NoSQL merely because traffic can grow.</p>
  <LessonHeading level={2} id="transactions">Transactions protect product invariants</LessonHeading><WorkedExample title="Reserve inventory and create an order together"><pre><code>{`BEGIN
  verify inventory is available
  decrement inventory
  insert order + payment-attempt record
COMMIT`}</code></pre><p>The transaction boundary should protect a named invariant such as “confirmed orders never exceed inventory.” Isolation choice and contention behavior still matter; review <Link href="/system-design/fundamentals/transactions">transactions</Link> and <Link href="/system-design/fundamentals/isolation-and-concurrency">concurrency</Link> rather than memorizing SQL syntax.</p></WorkedExample>
  <LessonHeading level={2} id="indexes-mvcc">Indexes and MVCC support useful concurrency</LessonHeading><p>B-tree indexes are a common default access path. Composite column order follows query shape; partial indexes cover selected rows; unique indexes or constraints protect uniqueness. Every index consumes storage and write work, so link the <Link href="/system-design/fundamentals/database-indexes">canonical index lesson</Link> before proposing more.</p><p>PostgreSQL uses MVCC so statements observe row versions according to transaction and isolation behavior. Readers do not simply block every writer. This improves concurrency but does not eliminate write conflicts, long transactions, cleanup, or the need to select isolation from invariants.</p>
  <LessonHeading level={2} id="replication">Primary and standbys separate write authority from read capacity</LessonHeading><MermaidDiagram chart={postgresArchitecture} title="PostgreSQL primary with streaming standbys" description="Application writes and correctness-sensitive reads go to the primary; write-ahead log records stream to two standbys that may serve staleness-tolerant reads." /><p>Streaming replication is asynchronous by default, so read replicas may lag and failover may lose recently committed-but-unreplicated changes. Synchronous configurations can wait for selected standby feedback, increasing durability confidence and write latency. PostgreSQL provides replication mechanisms; transparent automatic failover depends on the deployment and orchestration around it.</p>
  <LessonHeading level={2} id="scaling">Scale through the least complex effective step</LessonHeading><pre><code>{`indexes and query fixes
→ vertical capacity
→ caching
→ read replicas
→ table partitioning
→ application sharding only when justified`}</code></pre><p>Each step addresses a different bottleneck. Caching does not improve write contention; replicas do not scale the primary write path; partitioning a table is not automatically distributed sharding.</p>
  <LessonHeading level={2} id="fit">When it is—and is not—the best fit</LessonHeading><TradeoffTable><table><thead><tr><th>Good fit</th><th>A specialized system may fit better</th></tr></thead><tbody><tr><td>Related rows, constraints, joins, rich transactions, evolving queries</td><td>Enormous predictable key-only workload designed for a distributed KV service</td></tr><tr><td>Primary authoritative business data</td><td>Large object bytes, retained event streaming, or dedicated relevance search at scale</td></tr><tr><td>Structured and selected JSON use</td><td>A requirement whose operating model conflicts with one relational primary</td></tr></tbody></table></TradeoffTable><p>PostgreSQL can support many of the right-hand workloads at some scale. The question is operational and access-pattern fit, not whether a feature exists.</p>
  <CommonMistakes><ul><li>Jumping to NoSQL before testing indexes, queries, and capacity.</li><li>Calling read replicas immediately consistent.</li><li>Assuming replication includes automatic failover.</li><li>Adding indexes without accounting for write cost.</li><li>Confusing table partitioning with independent database shards.</li></ul></CommonMistakes>
  <InterviewFollowUps><ul><li>Which invariant requires a transaction?</li><li>What query does each index serve?</li><li>Can a replica return stale data to this user?</li><li>What happens if the primary fails before replication catches up?</li><li>At what measured bottleneck would sharding become justified?</li></ul></InterviewFollowUps>
  <TechnologyLessonEnd id="postgresql" practice={["payment-system", "ticketmaster", "url-shortener"]}>PostgreSQL is a strong relational default for constraints, transactions, joins, and evolving access patterns. Scale it progressively and state replica lag, failover, contention, and index costs.</TechnologyLessonEnd>
</>; }
