import { BadgeCheck, HandHeart, MessagesSquare, Trophy, Users } from "lucide-react";
import { FeatureCard, PageHero, SectionHeading } from "@/components/page-shell";
import { TrackedLink } from "@/components/tracked-action";
import { siteConfig } from "@/config/site";
import { createPageMetadata } from "@/lib/metadata";

export const metadata = createPageMetadata({ title: "Engineering Community", description: "Join engineers preparing, practicing, reviewing, and contributing together.", path: "/community" });
const areas = [{ icon: MessagesSquare, title: "Discord community", text: "A focused place for questions, study groups, and thoughtful engineering conversation." }, { icon: Users, title: "Mock interview peers", text: "Find practice partners and exchange structured feedback." }, { icon: HandHeart, title: "Mentors & reviewers", text: "A future home for office hours, portfolio review, and guidance." }, { icon: Trophy, title: "Weekly challenges", text: "Build and compare approaches across engineering disciplines." }, { icon: BadgeCheck, title: "Contributors", text: "Recognize the people improving resources, experiences, and community quality." }];
export default function CommunityPage() { return <><PageHero eyebrow="Community" title="A stronger interview journey, built together." description="Meet peers, practice openly, share what you learn, and help build an engineering community with useful signal."><TrackedLink href={siteConfig.discordUrl} event="discord_clicked" properties={{ placement:"community_hero" }}>Join Discord</TrackedLink></PageHero><section className="section"><div className="page-width"><div className="stat-grid"><div className="stat-card"><small>Engineers</small><strong>1,000+</strong><span>Placeholder community count</span></div><div className="stat-card"><small>Practice sessions</small><strong>—</strong><span>Tracking begins at launch</span></div><div className="stat-card"><small>Contributors</small><strong>—</strong><span>Program not launched</span></div><div className="stat-card"><small>Challenges</small><strong>—</strong><span>Weekly program upcoming</span></div></div></div></section><section className="section section-alt"><div className="page-width"><SectionHeading eyebrow="Ways to participate" title="Find your place in the Foundry." /><div className="feature-grid">{areas.map((area) => <FeatureCard icon={area.icon} title={area.title} description={area.text} label="Community" key={area.title} />)}</div></div></section><section className="final-cta" id="contributors"><div className="page-width"><div className="eyebrow"><Users size={13} />Contributors</div><h2>Help shape what this becomes.</h2><p>The contributor program, recognition model, and moderation process will be designed with the community before launch.</p><div className="hero-actions"><TrackedLink href={siteConfig.discordUrl} event="discord_clicked" properties={{ placement:"community_footer" }}>Join the conversation</TrackedLink></div></div></section></>; }
