begin;
create extension if not exists pgtap with schema extensions;
select plan(30);
select has_table('public', 'interview_reminder_preferences', 'preference table exists');
select has_table('public', 'interview_reminders', 'reminder table exists');
select has_table('public', 'interview_calendar_exports', 'export audit table exists');
select has_column('public', 'interview_rounds', 'calendar_revision', 'calendar revision exists');
select has_column('public', 'interview_rounds', 'reminder_schedule_revision', 'schedule revision exists');
select col_is_pk('public', 'interview_reminder_preferences', 'user_id', 'one preference per user');
select col_is_pk('public', 'interview_reminders', 'id', 'reminder id is primary key');
select has_index('public', 'interview_reminders', 'interview_reminders_due_email_idx', 'due claim index exists');
select has_index('public', 'interview_reminders', 'interview_reminders_user_round_idx', 'owner round index exists');
select has_index('public', 'interview_calendar_exports', 'interview_calendar_exports_user_round_idx', 'export index exists');
select ok((select relrowsecurity from pg_class where oid = 'public.interview_reminder_preferences'::regclass), 'preference RLS active');
select ok((select relrowsecurity from pg_class where oid = 'public.interview_reminders'::regclass), 'reminder RLS active');
select ok((select relrowsecurity from pg_class where oid = 'public.interview_calendar_exports'::regclass), 'export RLS active');
select is((select count(*)::integer from pg_policies where schemaname = 'public' and tablename = 'interview_reminder_preferences'), 1, 'preference owner policy only');
select is((select count(*)::integer from pg_policies where schemaname = 'public' and tablename = 'interview_reminders'), 1, 'reminder owner policy only');
select is((select count(*)::integer from pg_policies where schemaname = 'public' and tablename = 'interview_calendar_exports'), 1, 'export owner policy only');
select has_function('public', 'is_valid_iana_timezone', array['text'], 'timezone validator exists');
select has_function('public', 'save_interview_reminder_preferences', array['text','boolean','boolean','boolean','boolean','boolean'], 'preference RPC exists');
select has_function('public', 'record_interview_calendar_export', array['uuid','text'], 'export RPC exists');
select has_function('public', 'claim_due_interview_reminders', array['integer','timestamp with time zone'], 'claim RPC exists');
select has_function('public', 'validate_interview_reminder_claim', array['uuid','uuid'], 'claim validation RPC exists');
select has_function('public', 'mark_interview_reminder_delivered', array['uuid','uuid','text'], 'delivery RPC exists');
select has_function('public', 'fail_interview_reminder_delivery', array['uuid','uuid','text','boolean'], 'failure RPC exists');
select ok(has_function_privilege('authenticated', 'public.save_interview_reminder_preferences(text,boolean,boolean,boolean,boolean,boolean)', 'execute'), 'authenticated saves preferences');
select ok(has_function_privilege('authenticated', 'public.record_interview_calendar_export(uuid,text)', 'execute'), 'authenticated records export');
select ok(not has_function_privilege('authenticated', 'public.claim_due_interview_reminders(integer,timestamp with time zone)', 'execute'), 'authenticated cannot claim');
select ok(has_function_privilege('service_role', 'public.claim_due_interview_reminders(integer,timestamp with time zone)', 'execute'), 'service role can claim');
select ok(not has_table_privilege('anon', 'public.interview_reminders', 'select'), 'anonymous cannot read reminders');
select ok(not has_table_privilege('authenticated', 'public.interview_reminders', 'insert'), 'client cannot insert reminders');
select ok(not has_table_privilege('authenticated', 'public.interview_calendar_exports', 'update'), 'client cannot update exports');
select * from finish();
rollback;
