import Link from "next/link";
import { ArrowLeft, ArrowRight, CircleAlert, Copy, Lightbulb, ShieldCheck } from "lucide-react";
import { AnalyticsEventOnMount } from "@/components/analytics-event";
import { getSalaryNegotiationSources, type SalaryNegotiationModule } from "@/data/salary-negotiation";
import { SalaryNegotiationSourceNotes } from "@/features/salary-negotiation/source-notes";

export function SalaryNegotiationModuleView({ module, previousSlug, nextSlug }: { module: SalaryNegotiationModule; previousSlug?: string; nextSlug?: string }) {
  const sources = getSalaryNegotiationSources(module.slug);
  return <div className="salary-reading page-width"><AnalyticsEventOnMount event="salary_negotiation_module_viewed" properties={{ module_id: module.id }} /><nav className="salary-breadcrumbs" aria-label="Breadcrumb"><Link href="/salary-negotiation"><ArrowLeft size={14} />Salary Negotiation</Link><span>/ {module.title}</span></nav><header className="salary-reading-header"><h1>{module.title}</h1><p>{module.summary}</p><div><span>~{module.estimatedMinutes} min read</span><span>General educational guidance</span><span>{module.levels.join(" / ")}</span></div></header><aside className="salary-boundary"><ShieldCheck size={18} aria-hidden="true" /><div><strong>General education, not individualized advice</strong><p>Review your actual documents. Legal, tax, securities, immigration, and financial-planning questions can be time- and jurisdiction-sensitive; seek qualified advice where needed.</p></div></aside><aside className="salary-objectives"><h2>What you will practice</h2><ul>{module.objectives.map((objective) => <li key={objective}>{objective}</li>)}</ul></aside><article className="salary-article">{module.sections.map((item) => <section key={item.title}><h2>{item.title}</h2><p>{item.explanation}</p><div className="salary-example"><Lightbulb size={17} aria-hidden="true" /><div><strong>Example</strong><p>{item.example}</p></div></div><div className="salary-cautions"><CircleAlert size={17} aria-hidden="true" /><div><strong>Keep this in view</strong><ul>{item.cautions.map((caution) => <li key={caution}>{caution}</li>)}</ul></div></div></section>)}</article>{module.scripts.length > 0 && <section className="salary-scripts"><header><Copy size={18} aria-hidden="true" /><div><h2>Editable examples</h2><p>Adapt these to your true situation. They are review-and-copy starting points, not manipulative scripts.</p></div></header>{module.scripts.map((item) => <article key={item.title}><h3>{item.title}</h3><p><strong>Use when:</strong> {item.situation}</p><blockquote>{item.template}</blockquote></article>)}</section>}<SalaryNegotiationSourceNotes sources={sources} compact /><section className="salary-related"><h2>Keep working through the offer</h2><div>{module.relatedModuleSlugs.map((slug) => <Link href={`/salary-negotiation/${slug}`} key={slug}>Related module <ArrowRight size={14} /></Link>)}</div></section><nav className="salary-pager" aria-label="Module navigation">{previousSlug ? <Link href={`/salary-negotiation/${previousSlug}`}><span><ArrowLeft size={14} />Previous</span></Link> : <span />}{nextSlug ? <Link href={`/salary-negotiation/${nextSlug}`}>Next<ArrowRight size={14} /></Link> : <Link href="/salary-negotiation#compare-offers">Compare offers<ArrowRight size={14} /></Link>}</nav></div>;
}
