import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Binary, BookOpen, Building2, MessagesSquare, Network, Quote, UserRoundSearch } from "lucide-react";
import { companies } from "@/data/fixtures/companies";
import { FeatureCard, PageHero, SectionHeading, StatusPill } from "@/components/page-shell";

export function generateStaticParams() { return companies.map((company) => ({ slug: company.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const company = companies.find((item) => item.slug === slug); return { title: company ? `${company.name} Interview Guide` : "Company Guide", description: company?.description }; }
export default async function CompanyPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const company = companies.find((item) => item.slug === slug); if (!company) notFound(); const sections = [{ icon: Building2, title: "Interview overview", text: "Role-aware process overview and preparation scope." }, { icon: Binary, title: "DSA questions", text: "Company-tagged public practice links and original demo prompts." }, { icon: Network, title: "System Design", text: "Architecture themes and practice scenarios." }, { icon: MessagesSquare, title: "Behavioral", text: "Company-relevant preparation categories." }, { icon: Quote, title: "Experiences", text: "Community-submitted interview experiences." }, { icon: BookOpen, title: "Resources", text: "Attributed, useful preparation materials." }, { icon: UserRoundSearch, title: "Referral requests", text: "Voluntary community referral activity." }]; return <><PageHero eyebrow="Company interview guide" title={`${company.name} engineering interviews`} description={`A demo guide shell ready for verified process context, focused preparation, experiences, and resources. Engineering Foundry is not affiliated with ${company.name}.`}><StatusPill tone="accent">Demo content</StatusPill></PageHero><section className="section"><div className="page-width"><SectionHeading eyebrow="Guide architecture" title="Everything this guide will cover." description="No proprietary questions or unverifiable claims—only original, attributed, and community-submitted material." /><div className="feature-grid">{sections.map((section) => <FeatureCard icon={section.icon} title={section.title} description={section.text} label="Placeholder" key={section.title} />)}</div></div></section></>; }
