import { ConsensusLessonContent, DistributedLocksLessonContent, FailoverLessonContent, HealthChecksLessonContent, LeaderElectionLessonContent, LeasesFencingLessonContent, QuorumsLessonContent, RaftLessonContent } from "./coordination";
import { BackoffJitterLessonContent, BackpressureReliabilityLessonContent, BulkheadsLessonContent, CircuitBreakerLessonContent, FailureThinkingLessonContent, GracefulDegradationLessonContent, IdempotencyLessonContent, LoadSheddingLessonContent, RetriesLessonContent, TimeoutsLessonContent } from "./failure-resilience";
import { ActivePassiveActiveActiveLessonContent, DisasterRecoveryLessonContent, DistributedTransactionsLessonContent, MultiRegionLessonContent, PartialFailureLessonContent, RpoRtoLessonContent, SagaLessonContent, TwoPhaseCommitLessonContent } from "./transactions-regions";

export const reliabilityLessonIds = new Set(["failure-thinking", "timeouts", "retries", "exponential-backoff-jitter", "idempotency", "circuit-breaker", "bulkheads", "graceful-degradation", "load-shedding", "backpressure-reliability", "health-checks", "failover", "distributed-locks", "leases-fencing-tokens", "leader-election", "quorums", "distributed-consensus", "raft", "distributed-transactions", "two-phase-commit", "saga", "multi-region", "active-passive-active-active", "disaster-recovery", "rpo-rto", "partial-failure"]);

export function ReliabilityLessonContent({ lessonId }: { lessonId: string }) {
  switch (lessonId) {
    case "failure-thinking": return <FailureThinkingLessonContent />; case "timeouts": return <TimeoutsLessonContent />; case "retries": return <RetriesLessonContent />; case "exponential-backoff-jitter": return <BackoffJitterLessonContent />; case "idempotency": return <IdempotencyLessonContent />; case "circuit-breaker": return <CircuitBreakerLessonContent />; case "bulkheads": return <BulkheadsLessonContent />; case "graceful-degradation": return <GracefulDegradationLessonContent />; case "load-shedding": return <LoadSheddingLessonContent />; case "backpressure-reliability": return <BackpressureReliabilityLessonContent />; case "health-checks": return <HealthChecksLessonContent />; case "failover": return <FailoverLessonContent />; case "distributed-locks": return <DistributedLocksLessonContent />; case "leases-fencing-tokens": return <LeasesFencingLessonContent />; case "leader-election": return <LeaderElectionLessonContent />; case "quorums": return <QuorumsLessonContent />; case "distributed-consensus": return <ConsensusLessonContent />; case "raft": return <RaftLessonContent />; case "distributed-transactions": return <DistributedTransactionsLessonContent />; case "two-phase-commit": return <TwoPhaseCommitLessonContent />; case "saga": return <SagaLessonContent />; case "multi-region": return <MultiRegionLessonContent />; case "active-passive-active-active": return <ActivePassiveActiveActiveLessonContent />; case "disaster-recovery": return <DisasterRecoveryLessonContent />; case "rpo-rto": return <RpoRtoLessonContent />; case "partial-failure": return <PartialFailureLessonContent />; default: return null;
  }
}
