import { CollaborativeEditingLessonContent, CountMinSketchLessonContent, CrdtsLessonContent, BloomFiltersLessonContent, HyperLogLogLessonContent, OperationalTransformationLessonContent } from "./probabilistic-collaboration";
import { DistributedCountersLessonContent, JobSchedulersLessonContent, LeaderboardsLessonContent, MediaProcessingLessonContent, NotificationSystemsLessonContent, WebCrawlersLessonContent } from "./product-systems";
import { FullTextSearchLessonContent, GeohashingLessonContent, GeospatialSearchLessonContent, InvertedIndexesLessonContent, QuadtreesLessonContent, SearchAutocompleteLessonContent, SearchEngineConceptsLessonContent, TriesPrefixSearchLessonContent } from "./search-spatial";
import { ChoosingSpecializedBlocksLessonContent, EmbeddingsInfrastructureLessonContent, FeatureStoresLessonContent, ModelServingLessonContent, VectorSearchLessonContent } from "./ml-choice";

export const specializedLessonIds = new Set(["full-text-search", "inverted-indexes", "search-engine-concepts", "search-autocomplete", "tries-prefix-search", "geospatial-search", "geohashing", "quadtrees", "notification-delivery", "job-schedulers", "leaderboards", "distributed-counters", "web-crawling", "media-processing", "bloom-filters", "hyperloglog", "count-min-sketch", "collaborative-editing", "operational-transformation", "crdts", "vector-search", "embeddings-infrastructure", "model-serving", "feature-stores", "choosing-specialized-blocks"]);

export function SpecializedLessonContent({ lessonId }: { lessonId: string }) {
  switch (lessonId) {
    case "full-text-search": return <FullTextSearchLessonContent />; case "inverted-indexes": return <InvertedIndexesLessonContent />; case "search-engine-concepts": return <SearchEngineConceptsLessonContent />; case "search-autocomplete": return <SearchAutocompleteLessonContent />; case "tries-prefix-search": return <TriesPrefixSearchLessonContent />; case "geospatial-search": return <GeospatialSearchLessonContent />; case "geohashing": return <GeohashingLessonContent />; case "quadtrees": return <QuadtreesLessonContent />; case "notification-delivery": return <NotificationSystemsLessonContent />; case "job-schedulers": return <JobSchedulersLessonContent />; case "leaderboards": return <LeaderboardsLessonContent />; case "distributed-counters": return <DistributedCountersLessonContent />; case "web-crawling": return <WebCrawlersLessonContent />; case "media-processing": return <MediaProcessingLessonContent />; case "bloom-filters": return <BloomFiltersLessonContent />; case "hyperloglog": return <HyperLogLogLessonContent />; case "count-min-sketch": return <CountMinSketchLessonContent />; case "collaborative-editing": return <CollaborativeEditingLessonContent />; case "operational-transformation": return <OperationalTransformationLessonContent />; case "crdts": return <CrdtsLessonContent />; case "vector-search": return <VectorSearchLessonContent />; case "embeddings-infrastructure": return <EmbeddingsInfrastructureLessonContent />; case "model-serving": return <ModelServingLessonContent />; case "feature-stores": return <FeatureStoresLessonContent />; case "choosing-specialized-blocks": return <ChoosingSpecializedBlocksLessonContent />; default: return null;
  }
}
