import type { Metadata } from "next";
import { BriefcaseBusiness, Github, Linkedin, MapPin, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { AccountUnavailable } from "@/components/account-unavailable";
import { PublicProfileView } from "@/components/public-profile-view";
import { siteConfig } from "@/config/site";
import { isAccountPlatformAvailable } from "@/lib/account-platform";
import { getPublicProfile } from "@/lib/auth/queries";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ username: string }> }): Promise<Metadata> { if (!isAccountPlatformAvailable()) return { title: "Profile Not Found", robots: { index: false, follow: false } }; const username = (await params).username.toLowerCase(); const profile = await getPublicProfile(username); if (!profile) return { title: "Profile Not Found", robots: { index: false, follow: false } }; const title = `${profile.display_name} (@${profile.username}) — Engineering Foundry`; const description = profile.bio ?? `${profile.display_name} is a member of the Engineering Foundry community.`; return { title: { absolute: title }, description, alternates: { canonical: `${siteConfig.url}/u/${profile.username}` }, openGraph: { title, description, url: `${siteConfig.url}/u/${profile.username}`, type: "profile" }, robots: { index: true, follow: true } }; }

export default async function ProfilePage({ params }: { params: Promise<{ username: string }> }) {
  if (!isAccountPlatformAvailable()) return <AccountUnavailable />;
  const profile = await getPublicProfile((await params).username);
  if (!profile) notFound();
  const initials = (profile.display_name ?? profile.username ?? "EF").split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  return <><PublicProfileView username={profile.username!} /><section className="public-profile-hero"><div className="page-width public-profile-heading"><div className="profile-avatar">{initials}</div><div><p className="auth-kicker">Engineering Foundry member</p><h1>{profile.display_name}</h1><span>@{profile.username}</span></div></div></section><section className="section"><div className="page-width public-profile-layout"><article className="profile-about"><p className="auth-kicker">About</p><h2>Engineering profile</h2><p className="profile-bio">{profile.bio ?? "This member has not added a bio yet."}</p><div className="profile-facts">{profile.current_role && <div><BriefcaseBusiness size={17} /><span><small>Current role</small><strong>{profile.current_role}</strong></span></div>}{profile.current_company && <div><MapPin size={17} /><span><small>Current company</small><strong>{profile.current_company}</strong></span></div>}{profile.years_experience !== null && <div><UserRound size={17} /><span><small>Experience</small><strong>{profile.years_experience} {profile.years_experience === 1 ? "year" : "years"}</strong></span></div>}</div></article><aside className="profile-links panel"><h2>Connect</h2>{profile.github_url && <a className="button button-secondary" href={profile.github_url} rel="noopener noreferrer" target="_blank"><Github size={16} />GitHub</a>}{profile.linkedin_url && <a className="button button-secondary" href={profile.linkedin_url} rel="noopener noreferrer" target="_blank"><Linkedin size={16} />LinkedIn</a>}{!profile.github_url && !profile.linkedin_url && <p className="muted">No professional links shared.</p>}<div className="profile-privacy-note">Only information this member chose to make public is shown here.</div></aside></div></section><section className="section section-alt"><div className="page-width"><div className="empty-state"><UserRound size={22} /><strong>Activity modules are coming later</strong><p>Preparation progress, mocks, referrals, and challenge contributions are not fabricated or exposed in this identity phase.</p></div></div></section></>;
}
