import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Plus } from "lucide-react";
import { AccountUnavailable } from "@/components/account-unavailable";
import { BehavioralWorkspaceHeader } from "@/features/behavioral/workspace-header";
import { isAccountPlatformAvailable } from "@/lib/account-platform";
import { requireMemberProfile } from "@/lib/auth/guards";
import { getBehavioralWorkspaceData } from "@/lib/behavioral/queries";
import { STORY_READINESS, STORY_THEMES } from "@/lib/behavioral/options";
import { storyReadiness } from "@/lib/behavioral/readiness";
export const metadata: Metadata = { title: "Behavioral story bank", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

export default async function BehavioralStoriesPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; theme?: string; context?: string }> }) {
  if (!isAccountPlatformAvailable()) return <AccountUnavailable />; await requireMemberProfile("/behavioral/stories"); const params = await searchParams; const data = await getBehavioralWorkspaceData(); const q = params.q?.toLowerCase().trim() ?? "";
  const contexts = Array.from(new Set(data.stories.map((story) => story.company_or_context).filter(Boolean) as string[])).sort();
  const stories = data.stories.filter((story) => { const themes = data.themes.filter((theme) => theme.story_id === story.id).map((theme) => theme.theme); return (!q || `${story.title} ${story.company_or_context ?? ""} ${story.project ?? ""} ${story.short_summary ?? ""} ${themes.join(" ")}`.toLowerCase().includes(q)) && (!params.status || storyReadiness(story) === params.status) && (!params.theme || themes.includes(params.theme)) && (!params.context || story.company_or_context === params.context); });
  return <div className="behavioral-workspace"><div className="page-width"><BehavioralWorkspaceHeader title="STAR story bank" description="Build a compact library of real examples, then reuse each story across several behavioral questions." /><div className="behavioral-toolbar"><form className="behavioral-filters"><div><label htmlFor="story-search">Search</label><input id="story-search" name="q" type="search" defaultValue={params.q} placeholder="Title, project, theme…" /></div><div><label htmlFor="story-status-filter">Readiness</label><select id="story-status-filter" name="status" defaultValue={params.status ?? ""}><option value="">Any readiness</option>{STORY_READINESS.map((status) => <option key={status}>{status}</option>)}</select></div><div><label htmlFor="story-theme-filter">Theme</label><select id="story-theme-filter" name="theme" defaultValue={params.theme ?? ""}><option value="">Any theme</option>{STORY_THEMES.map((theme) => <option key={theme}>{theme}</option>)}</select></div><div><label htmlFor="story-context-filter">Context</label><select id="story-context-filter" name="context" defaultValue={params.context ?? ""}><option value="">Any context</option>{contexts.map((context) => <option key={context}>{context}</option>)}</select></div><button className="button button-secondary button-sm">Apply</button></form><Link className="button button-sm" href="/behavioral/stories/new"><Plus size={15} />New story</Link></div>
    {stories.length ? <section className="behavioral-story-list">{stories.map((story) => { const themes = data.themes.filter((theme) => theme.story_id === story.id); const linked = data.links.filter((link) => link.story_id === story.id).length; const readiness = storyReadiness(story); return <article key={story.id}><div><div className="behavioral-card-meta"><span>{readiness}</span>{story.company_or_context && <span>{story.company_or_context}</span>}{story.role && <span>{story.role}</span>}</div><h2>{story.title}</h2><p>{story.short_summary || story.situation || "Start filling the STAR outline when the details are fresh."}</p><div className="behavioral-theme-tags">{themes.map((theme) => <span key={theme.id}>{theme.theme}</span>)}</div></div><footer><small>{linked} linked {linked === 1 ? "question" : "questions"} · Updated {new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(story.updated_at))}</small><Link href={`/behavioral/stories/${story.id}`}>Open story<ArrowRight size={14} /></Link></footer></article>; })}</section> : <div className="tracker-empty"><h2>{data.stories.length ? "No stories match" : "Build your first reusable story"}</h2><p>A strong bank starts with one specific project, disagreement, failure, or decision.</p><Link className="button button-sm" href="/behavioral/stories/new"><Plus size={15} />Create story</Link></div>}
  </div></div>;
}
