"use client";

import { useMemo, useState } from "react";
import { SearchCheck } from "lucide-react";
import type { PublicInterviewExperienceAvailability } from "@/lib/supabase/public";

export type PublicExperience = { id: string; company_name: string; role_title: string; role_level: string | null; region: string | null; interview_date: string | null; summary: string; preparation_lessons: string | null; public_identity: "anonymous" | "username"; interview_experience_rounds: { round_type: string; topic_labels: string[] }[] | null };

export function ExperienceDirectory({ availability, experiences }: { availability: PublicInterviewExperienceAvailability; experiences: readonly PublicExperience[] }) {
  const [company, setCompany] = useState(""); const [level, setLevel] = useState(""); const [region, setRegion] = useState(""); const [stage, setStage] = useState("");
  const visible = useMemo(() => experiences.filter((experience) => (!company || experience.company_name === company) && (!level || experience.role_level === level) && (!region || experience.region === region) && (!stage || experience.interview_experience_rounds?.some((round) => round.round_type === stage))), [company, experiences, level, region, stage]);
  const companies = [...new Set(experiences.map((item) => item.company_name))].sort(); const levels = [...new Set(experiences.map((item) => item.role_level).filter(Boolean))] as string[]; const regions = [...new Set(experiences.map((item) => item.region).filter(Boolean))] as string[]; const stages = [...new Set(experiences.flatMap((item) => item.interview_experience_rounds?.map((round) => round.round_type) ?? []))];
  if (availability === "unavailable") return <div className="experience-directory-empty" role="alert"><SearchCheck size={25} /><div><strong>Reviewed reports are temporarily unavailable.</strong><p>We could not verify a complete directory right now. Try again later; this message does not mean that no reports are published.</p></div></div>;
  if (availability === "unconfigured") return <div className="experience-directory-empty" role="status"><SearchCheck size={25} /><div><strong>Reviewed reports are unavailable in this environment.</strong><p>The public publication service is not configured here, so this page cannot make a completeness claim.</p></div></div>;
  if (!experiences.length) return <div className="experience-directory-empty" role="status"><SearchCheck size={25} /><div><strong>No reviewed public interview experiences are published yet.</strong><p>Engineering Foundry does not use demo accounts, scraped reviews, or invented activity to make this directory look populated. The first reports will appear after contributor submission and moderation.</p></div></div>;
  return <><div className="experience-directory-filters" aria-label="Filter reviewed interview experiences"><label>Company<select value={company} onChange={(event) => setCompany(event.target.value)}><option value="">All companies</option>{companies.map((item) => <option key={item}>{item}</option>)}</select></label><label>Level<select value={level} onChange={(event) => setLevel(event.target.value)}><option value="">All levels</option>{levels.map((item) => <option key={item}>{item}</option>)}</select></label><label>Region<select value={region} onChange={(event) => setRegion(event.target.value)}><option value="">All regions</option>{regions.map((item) => <option key={item}>{item}</option>)}</select></label><label>Stage<select value={stage} onChange={(event) => setStage(event.target.value)}><option value="">All stages</option>{stages.map((item) => <option key={item}>{item}</option>)}</select></label></div>{visible.length ? <div className="experience-directory-list">{visible.map((experience) => <article className="experience-directory-entry" key={experience.id}><header><div><h2>{experience.company_name}</h2><p>{experience.role_title}{experience.role_level ? ` · ${experience.role_level}` : ""}{experience.region ? ` · ${experience.region}` : ""}</p></div><span>{experience.interview_date ? new Intl.DateTimeFormat("en", { month: "short", year: "numeric" }).format(new Date(`${experience.interview_date}T00:00:00`)) : "Date not provided"}</span></header><p>{experience.summary}</p>{experience.interview_experience_rounds?.length ? <dl>{experience.interview_experience_rounds.map((round, index) => <div key={`${round.round_type}-${index}`}><dt>{round.round_type}</dt><dd>{round.topic_labels.length ? round.topic_labels.join(" · ") : "High-level process context"}</dd></div>)}</dl> : null}{experience.preparation_lessons ? <details><summary>Preparation lessons</summary><p>{experience.preparation_lessons}</p></details> : null}<footer>{experience.public_identity === "anonymous" ? "Published anonymously" : "Contributor chose username visibility"} · Reviewed contributor report</footer></article>)}</div> : <div className="experience-directory-empty" role="status"><div><strong>No reports match these filters.</strong><p>Clear a filter to see all reviewed reports.</p></div></div>}</>;
}
