"use client";

import { useMemo, useState } from "react";
import { SearchCheck } from "lucide-react";
import { canonicalInterviewExperienceCompany, normalizeInterviewExperienceCompany } from "@/lib/interview-experiences/company";

export type PublicExperience = { id: string; company_name: string; role_title: string; role_level: string | null; region: string | null; interview_date: string | null; summary: string; preparation_lessons: string | null; public_identity: "anonymous" | "username"; interview_experience_rounds: { round_type: string; topic_labels: string[]; process_notes: string | null }[] | null };

const resolveCompanyFilter = (requested: string, companies: readonly string[]) => companies.find((company) => normalizeInterviewExperienceCompany(company) === normalizeInterviewExperienceCompany(requested)) ?? canonicalInterviewExperienceCompany(requested);

export function ExperienceDirectory({ experiences, initialCompany = "", fixedCompany = false }: { experiences: readonly PublicExperience[]; initialCompany?: string; fixedCompany?: boolean }) {
  const companies = useMemo(() => [...new Set(experiences.map((item) => item.company_name))].sort(), [experiences]);
  const requestedCompany = useMemo(() => resolveCompanyFilter(initialCompany, companies), [companies, initialCompany]);
  const [company, setCompany] = useState(requestedCompany); const [level, setLevel] = useState(""); const [region, setRegion] = useState(""); const [stage, setStage] = useState("");
  const visible = useMemo(() => experiences.filter((experience) => (!company || normalizeInterviewExperienceCompany(experience.company_name) === normalizeInterviewExperienceCompany(company)) && (!level || experience.role_level === level) && (!region || experience.region === region) && (!stage || experience.interview_experience_rounds?.some((round) => round.round_type === stage))), [company, experiences, level, region, stage]);
  const levels = [...new Set(experiences.map((item) => item.role_level).filter(Boolean))] as string[]; const regions = [...new Set(experiences.map((item) => item.region).filter(Boolean))] as string[]; const stages = [...new Set(experiences.flatMap((item) => item.interview_experience_rounds?.map((round) => round.round_type) ?? []))];
  const filtersActive = Boolean((!fixedCompany && company) || level || region || stage);
  const resetFilters = () => { if (!fixedCompany) setCompany(""); setLevel(""); setRegion(""); setStage(""); };
  if (!experiences.length) return <div className="experience-directory-empty" role="status"><SearchCheck size={25} /><div><strong>No reviewed public interview experiences are published yet.</strong><p>Engineering Foundry does not use demo accounts, scraped reviews, or invented activity to make this directory look populated. The first reports will appear after contributor submission and moderation.</p></div></div>;
  return <><fieldset className="experience-directory-filters"><legend>Filter reviewed interview experiences</legend>{!fixedCompany && <label>Company<select value={company} onChange={(event) => setCompany(event.target.value)}><option value="">All companies</option>{company && !companies.includes(company) && <option value={company}>{company}</option>}{companies.map((item) => <option key={item}>{item}</option>)}</select></label>}<label>Level<select value={level} onChange={(event) => setLevel(event.target.value)}><option value="">All levels</option>{levels.map((item) => <option key={item}>{item}</option>)}</select></label><label>Region<select value={region} onChange={(event) => setRegion(event.target.value)}><option value="">All regions</option>{regions.map((item) => <option key={item}>{item}</option>)}</select></label><label>Stage<select value={stage} onChange={(event) => setStage(event.target.value)}><option value="">All stages</option>{stages.map((item) => <option key={item}>{item}</option>)}</select></label></fieldset><div role="status" aria-live="polite">{visible.length} {visible.length === 1 ? "reviewed report" : "reviewed reports"}{fixedCompany ? ` for ${company || initialCompany}.` : filtersActive ? " match the current filters." : " available."}</div>{filtersActive && <button className="button button-ghost" type="button" onClick={resetFilters}>Reset filters</button>}{visible.length ? <div className="experience-directory-list">{visible.map((experience) => <article className="experience-directory-entry" key={experience.id}><header><div><h2>{experience.company_name}</h2><p>{experience.role_title}{experience.role_level ? ` · ${experience.role_level}` : ""}{experience.region ? ` · ${experience.region}` : ""}</p></div><span>{experience.interview_date ? new Intl.DateTimeFormat("en", { month: "short", year: "numeric" }).format(new Date(`${experience.interview_date}T00:00:00`)) : "Date not provided"}</span></header><p>{experience.summary}</p>{experience.interview_experience_rounds?.length ? <dl>{experience.interview_experience_rounds.map((round, index) => <div key={`${round.round_type}-${index}`}><dt>{round.round_type}</dt><dd>{round.topic_labels.length ? round.topic_labels.join(" · ") : "High-level process context"}</dd></div>)}</dl> : null}{experience.preparation_lessons ? <details><summary>Preparation lessons</summary><p>{experience.preparation_lessons}</p></details> : null}<footer>{experience.public_identity === "anonymous" ? "Published anonymously" : "Contributor chose username visibility"} · Reviewed contributor report</footer></article>)}</div> : <div className="experience-directory-empty" role="status"><div><strong>{company ? `No reviewed public ${company} interview experiences are published yet.` : "No reports match these filters."}</strong><p>{company ? "This selected-company view does not substitute unrelated reports." : "Reset filters to see all reviewed reports."}</p></div></div>}</>;
}
