"use client";

/* DIRECTION CONTRACT — private evidence worksheet in the existing DSA paper world; seed f31e86c0. */
import Link from "next/link";
import { Check, Clock3, LoaderCircle, LockKeyhole, Pause, Play, RotateCcw } from "lucide-react";
import { startTransition, useActionState, useEffect, useRef, useState, type FormEvent } from "react";
import { dsaErrorRecoveryStates, dsaPracticeCheckpoints, dsaPracticeModeDefinitions, dsaRubricBands, dsaRubricDimensions, dsaRubricGroups, type DsaPracticeAttempt, type DsaPracticeMode } from "@/lib/dsa/practice-attempt";
import { saveDsaPracticeAttemptAction, type DsaAttemptActionState } from "./actions";

const checkpointLabels = { clarified: "Clarification recorded", brute_force: "Brute force stated", plan_before_code: "Plan before code", implemented: "Implementation attempted", tested: "Tests narrated", complexity: "Complexity stated" } as const;
const bandLabels = { needs_evidence: "Needs evidence", developing: "Developing", strong: "Strong" } as const;
const recoveryLabels = { not_needed: "No recovery needed", recovered: "Found and repaired an error", unresolved: "Error remains unresolved" } as const;
function clock(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export function DsaPracticeAttemptEditor({ attempt, questionTitle }: { attempt: DsaPracticeAttempt; questionTitle: string }) {
  const action = saveDsaPracticeAttemptAction.bind(null, attempt.id, attempt.question_id);
  const [mode, setMode] = useState<DsaPracticeMode>(attempt.mode); const [duration, setDuration] = useState(attempt.duration_minutes ?? 45);
  const [elapsed, setElapsed] = useState(attempt.elapsed_seconds); const [running, setRunning] = useState(false); const [timerVisible, setTimerVisible] = useState(true); const [dirty, setDirty] = useState(false);
  const [state, formAction, pending] = useActionState(async (previous: DsaAttemptActionState, formData: FormData) => { const result = await action(previous, formData); if (result.status === "success") setDirty(false); return result; }, { status: "idle", message: "", revision: attempt.revision } satisfies DsaAttemptActionState);
  const submitting = useRef(false);
  useEffect(() => { if (!running) return; const id = window.setInterval(() => setElapsed((value) => Math.min(86400, value + 1)), 1000); return () => window.clearInterval(id); }, [running]);
  useEffect(() => { if (!pending) submitting.current = false; }, [pending]);
  useEffect(() => { const unload = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; const links = (event: MouseEvent) => { const link = (event.target as Element | null)?.closest("a"); if (dirty && link?.href && !window.confirm("Leave without saving this DSA attempt?")) event.preventDefault(); }; window.addEventListener("beforeunload", unload); document.addEventListener("click", links, true); return () => { window.removeEventListener("beforeunload", unload); document.removeEventListener("click", links, true); }; }, [dirty]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (submitting.current || state.conflict) return; submitting.current = true; setRunning(false); startTransition(() => formAction(new FormData(event.currentTarget))); };
  const remaining = Math.max(0, duration * 60 - elapsed);
  const errorId = state.status === "error" ? "dsa-attempt-error" : undefined;
  return <form action={formAction} onSubmit={submit} onChange={() => setDirty(true)} className="dsa-attempt-editor" aria-busy={pending} data-impeccable-seed="f31e86c0">
    <input type="hidden" name="expected_revision" value={state.revision ?? attempt.revision} /><input type="hidden" name="elapsed_seconds" value={elapsed} />
    <header className="dsa-attempt-editor-header"><div><Link href={`/dsa/questions/${attempt.question_id}`}>← {questionTitle}</Link><span>PRIVATE ATTEMPT · FOUNDRY 75 v{attempt.catalog_version}</span><input aria-label="Attempt title" name="title" maxLength={160} required defaultValue={attempt.title} aria-describedby={errorId} /></div><div><label>Status<select name="status" defaultValue={attempt.status}><option value="draft">Draft</option><option value="completed">Completed self-review</option><option value="review">Return to review queue</option></select></label><label>Mode<select name="mode" value={mode} onChange={(event) => setMode(event.target.value as DsaPracticeMode)}>{dsaPracticeModeDefinitions.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label>{mode === "timed" ? <label>Minutes<input name="duration_minutes" type="number" min={10} max={120} value={duration} onChange={(event) => setDuration(Math.min(120, Math.max(10, Number(event.target.value) || 10)))} /></label> : <input type="hidden" name="duration_minutes" value="" />}<label>Prior exposure<select name="prior_exposure" defaultValue={attempt.prior_exposure}><option value="unseen">Unseen prompt</option><option value="prompt_seen">Prompt seen</option><option value="solution_seen">Solution reviewed</option><option value="solved_before">Solved before</option></select></label></div></header>
    <aside className="dsa-attempt-private"><LockKeyhole size={16} /><p><strong>Private to your account.</strong> Notes, implementation, reflection, and rubric evidence are excluded from analytics. Your export includes this record; account deletion removes it.</p></aside>
    <section className="dsa-attempt-clock" aria-label="Practice timer"><Clock3 size={17} /><div><strong>{timerVisible ? (mode === "timed" ? clock(remaining) : clock(elapsed)) : "Timer hidden"}</strong><span>{timerVisible ? `${running ? "Running" : "Paused"} · elapsed ${clock(elapsed)}` : "Paused · time display disabled"}</span></div><button type="button" onClick={() => { setDirty(true); setRunning((value) => !value); }}>{running ? <Pause size={14} /> : <Play size={14} />}{running ? "Pause" : "Start"}</button>{mode === "timed" && <button type="button" onClick={() => { setDirty(true); setDuration((value) => Math.min(120, value + 5)); }}>Extend 5 min</button>}<button type="button" onClick={() => { setDirty(true); setRunning(false); setElapsed(0); }}><RotateCcw size={14} />Reset</button><button type="button" aria-pressed={!timerVisible} onClick={() => { setRunning(false); setTimerVisible((value) => !value); }}>{timerVisible ? "Disable display" : "Show timer"}</button></section>
    <div className="dsa-attempt-layout"><div className="dsa-attempt-sections">
      <section><header><span>01</span><div><h2>Reason before code</h2><p>Capture only the decisions that changed your approach.</p></div></header><label>Clarification and framing<textarea name="clarification_notes" rows={5} maxLength={8000} defaultValue={attempt.document.clarification_notes} /></label><label>Brute-force baseline<textarea name="brute_force_notes" rows={5} maxLength={8000} defaultValue={attempt.document.brute_force_notes} /></label><label>Invariant and plan before code<textarea name="approach_notes" rows={7} maxLength={8000} defaultValue={attempt.document.approach_notes} /></label></section>
      <section><header><span>02</span><div><h2>Implement and validate</h2><p>Keep private code here only if it helps your rehearsal; it is never sent to analytics.</p></div></header><label>Implementation notes or code<textarea name="implementation_notes" rows={14} maxLength={30000} spellCheck={false} defaultValue={attempt.document.implementation_notes} /></label><label>Tests and edge cases<textarea name="test_notes" rows={6} maxLength={8000} defaultValue={attempt.document.test_notes} /></label><label>Final complexity and assumptions<textarea name="complexity_notes" rows={4} maxLength={8000} defaultValue={attempt.document.complexity_notes} /></label></section>
      <section><header><span>03</span><div><h2>Attempt evidence</h2><p>Checks describe what happened. They do not turn completion into mastery.</p></div></header><fieldset className="dsa-attempt-checkpoints"><legend>Completed checkpoints</legend>{dsaPracticeCheckpoints.map((checkpoint) => <label key={checkpoint}><input type="checkbox" name={`checkpoint_${checkpoint}`} value="yes" defaultChecked={attempt.document.completed_checkpoints.includes(checkpoint)} /><span>{checkpointLabels[checkpoint]}</span></label>)}</fieldset><div className="dsa-attempt-evidence-row"><label>Hints used<input name="hints_used" type="number" min={0} max={20} defaultValue={attempt.document.hints_used} /></label><label>Error recovery<select name="error_recovery" defaultValue={attempt.document.error_recovery}>{dsaErrorRecoveryStates.map((value) => <option value={value} key={value}>{recoveryLabels[value]}</option>)}</select></label></div><label>Reflection<textarea name="reflection" rows={6} maxLength={8000} defaultValue={attempt.document.reflection} placeholder="What failed, what changed, and what should be retrieved later?" /></label></section>
      <section><header><span>04</span><div><h2>12-dimension self-review</h2><p>Use the four groups to scan the attempt. Each dimension stays independent; no total is calculated.</p></div></header>{dsaRubricGroups.map((group) => <fieldset className="dsa-attempt-rubric-group" key={group.id}><legend>{group.label}</legend>{group.dimensionIds.map((id) => { const dimension = dsaRubricDimensions.find(([candidate]) => candidate === id)!; return <div key={id}><label><span><strong>{dimension[1]}</strong><small>{dimension[2]}</small></span><select aria-label={`${dimension[1]} band`} name={`review_${id}`} defaultValue={attempt.document.self_review[id] ?? ""}><option value="">Not reviewed</option>{dsaRubricBands.map((band) => <option value={band} key={band}>{bandLabels[band]}</option>)}</select></label><label>Evidence<textarea name={`evidence_${id}`} rows={2} maxLength={4000} defaultValue={attempt.document.dimension_evidence[id] ?? ""} /></label></div>; })}</fieldset>)}</section>
      <section><header><span>05</span><div><h2>Next retrieval</h2><p>Turn one observed gap into a specific next action.</p></div></header><label>Follow-up or review cue<textarea name="follow_up" rows={5} maxLength={8000} defaultValue={attempt.document.follow_up} /></label><div className="dsa-attempt-return"><Link href="/dsa/practice?mode=review">Return to review queue</Link><Link href="/interview-playbook">Return evidence to Interview Playbook</Link></div></section>
    </div><nav aria-label="Attempt sections"><strong>Worksheet</strong><a href="#top">Setup</a><a href="#dsa-attempt-save">Save record</a></nav></div>
    <footer className="dsa-attempt-savebar" id="dsa-attempt-save"><div role={state.status === "error" ? "alert" : "status"} aria-live={state.status === "error" ? "assertive" : "polite"}>{dirty ? "Unsaved changes" : state.status === "success" ? <><Check size={14} />Saved</> : "No unsaved changes"}{state.message && <small id={errorId}>{state.message}{state.conflict && <><br /><Link href={`/dsa/questions/${attempt.question_id}/practice/${attempt.id}`} target="_blank">Review latest in a new tab</Link></>}</small>}</div><button className="button" type="submit" aria-disabled={pending || Boolean(state.conflict)}>{pending ? <><LoaderCircle className="spin" size={15} />Saving…</> : "Save attempt"}</button></footer>
  </form>;
}
