import Link from "next/link";
import { ArrowRight, BookOpen, Code2, Layers3, Network, ShieldCheck } from "lucide-react";
import { createPageMetadata } from "@/lib/metadata";
import { lowLevelDesignFramework, lowLevelDesignInterviewTimeVersion, lowLevelDesignLessons, lowLevelDesignLevels, lowLevelDesignPractice } from "@/data/low-level-design";

export const metadata = createPageMetadata({ title: "Low-Level Design Interview Preparation", description: "Learn object and component design for interviews through an eight-lesson curriculum, a reusable reasoning framework, and six original practice designs.", path: "/low-level-design" });

export default function LowLevelDesignPage() {
  return <div className="lld-home">
    <section className="lld-home-intro"><div className="page-width"><div><h1>Design behavior that can survive a follow-up.</h1><p className="lld-lede">Low-Level Design is about requirements, responsibilities, interfaces, state, failure behavior, and trade-offs under interview constraints—not distributed architecture, language trivia, or memorized patterns.</p><nav aria-label="Low-Level Design start actions"><Link className="button" href={`/low-level-design/lessons/${lowLevelDesignLessons[0].slug}`}>Start the curriculum <ArrowRight size={16} /></Link><Link className="button button-secondary" href="/low-level-design/practice">Choose a practice design</Link></nav></div><aside className="lld-home-boundary"><Layers3 size={22} aria-hidden="true" /><h2>Keep the boundary clear</h2><dl><div><dt>Low-Level Design</dt><dd>Internal responsibilities, interfaces, state, and testability.</dd></div><div><dt>System Design</dt><dd>Distributed architecture, storage, traffic, availability, and network boundaries.</dd></div><div><dt>Later systems work</dt><dd>Memory, kernel behavior, cache coherence, and low-level implementation internals.</dd></div></dl><Link href="/system-design/start-here/introduction">When distributed concerns take over <ArrowRight size={14} /></Link></aside></div></section>
    <section className="lld-home-section"><div className="page-width"><header><h2>What should you do next?</h2><p>Choose a lesson when you need a reasoning tool. Choose a practice design when you are ready to explain an approach aloud.</p></header><div className="lld-next-grid"><Link href={`/low-level-design/lessons/${lowLevelDesignLessons[0].slug}`}><BookOpen size={21} /><h3>Learn the interview flow</h3><p>Start with a bounded, revisable way to go from use cases to a validated design.</p><span>Read lesson <ArrowRight size={14} /></span></Link><Link href={`/low-level-design/practice/${lowLevelDesignPractice[0].slug}`}><Code2 size={21} /><h3>Practice a full design</h3><p>Work through parking allocation with progressive hints instead of a pre-revealed answer.</p><span>Open practice <ArrowRight size={14} /></span></Link><Link href="/interview-tips/rounds/low-level-design"><ShieldCheck size={21} /><h3>Rehearse in-round execution</h3><p>Use the Playbook dossier for scoping, communication, recovery, and closing a live LLD round.</p><span>Open execution guide <ArrowRight size={14} /></span></Link></div></div></section>
    <section className="lld-home-section lld-home-alt"><div className="page-width"><header><h2>The eight-lesson curriculum</h2><p>Each lesson pairs a concrete example with common mistakes, trade-offs, follow-ups, and a clear stopping point.</p></header><ol className="lld-curriculum-list">{lowLevelDesignLessons.map((lesson, index) => <li key={lesson.id}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{lesson.title}</h3><p>{lesson.summary}</p><small>{lesson.estimatedMinutes} min · {lesson.levels.join(" / ")}</small></div><Link href={`/low-level-design/lessons/${lesson.slug}`} aria-label={`Open ${lesson.title}`}><ArrowRight size={17} /></Link></li>)}</ol></div></section>
    <section className="lld-home-section"><div className="page-width lld-framework-layout"><div><h2>A reusable interview framework</h2><p>Use this as a rehearsal guide, not a rigid script. Go back to an earlier step when a use case or follow-up reveals a bad assumption.</p><ol className="lld-framework">{lowLevelDesignFramework.map(([label, description], index) => <li key={label}><span>{index + 1}</span><div><h3>{label}</h3><p>{description}</p></div></li>)}</ol></div><aside><h2>Compact interview-time version</h2><ol>{lowLevelDesignInterviewTimeVersion.map((step) => <li key={step}>{step}</li>)}</ol><p>Completion records on this section are self-recorded preparation activity, never evidence of mastery or performance.</p></aside></div></section>
    <section className="lld-home-section lld-home-alt"><div className="page-width"><header><h2>Six original practice designs</h2><p>Each exercise introduces a different design pressure and keeps its example approach progressively disclosed.</p></header><div className="lld-practice-list">{lowLevelDesignPractice.map((problem) => <Link href={`/low-level-design/practice/${problem.slug}`} key={problem.id}><div><h3>{problem.title}</h3><p>{problem.summary}</p><small>{problem.reasoningAreas.slice(0, 3).join(" · ")}</small></div><ArrowRight size={17} /></Link>)}</div><Link className="lld-text-link" href="/low-level-design/practice">Browse the practice library <ArrowRight size={15} /></Link></div></section>
    <section className="lld-home-section"><div className="page-width"><header><h2>Calibrate the depth, not the class count</h2><p>Every level still needs a coherent primary flow and validation. The difference is the judgment expected around ambiguity, evolution, and boundaries.</p></header><div className="lld-level-grid">{lowLevelDesignLevels.map((level) => <article key={level}><h3>{level}</h3><p>{level === "Entry" ? "Sensible entities and responsibilities, basic interfaces and state, and clear communication." : level === "Mid" ? "Stronger abstractions, error behavior, extension points, and testability." : level === "Senior" ? "Ambiguity, lifecycle, concurrency where it matters, trade-offs, and evolution." : "Scope judgment, system and organizational boundaries, and avoiding needless complexity."}</p></article>)}</div><p className="lld-secondary-note"><Network size={16} aria-hidden="true" />LLD stays a secondary public preparation surface in v1. It is discoverable and records local self-reported activity, but it does not alter P0.2’s four primary continuation tracks or claim durable signed-in progress without a dedicated schema.</p></div></section>
  </div>;
}
