import Link from "next/link";
import { ArrowRight, ExternalLink, ShieldCheck } from "lucide-react";
import type { CompanyGuideV1 } from "@/data/company-guides/v1";
import type { PublicInterviewExperienceAvailability } from "@/lib/supabase/public";

export type CompanyGuidePublicExperience = { id: string; role_title: string; role_level: string | null; region: string | null; interview_date: string | null; summary: string; interview_experience_rounds: { round_type: string; topic_labels: string[] }[] | null };

const labels = { official: "Official source", candidate: "Candidate-reported", recommendation: "Engineering Foundry recommendation" } as const;

export function CompanyGuideV1Workspace({ accountPlatformAvailable, experienceAvailability, guide, experiences }: { accountPlatformAvailable: boolean; experienceAvailability: PublicInterviewExperienceAvailability; guide: CompanyGuideV1; experiences: CompanyGuidePublicExperience[] }) {
  const sources = new Map(guide.sources.map((source) => [source.id, source]));
  return <main className="company-v1">
    <header className="company-v1-hero"><div className="page-width"><Link href="/companies" className="text-link">All company guides</Link><h1>{guide.company} engineering interview guide</h1><p>{guide.overview}</p><div className="company-v1-meta"><span>{guide.publicationKind === "neutral-hub" ? "Neutral evidence hub" : "Sourced guide"}</span><span>Verified {guide.verifiedAt}</span><span>Role, team, location, and time may change the process.</span></div><a className="button button-secondary" href={guide.sources[0].url} target="_blank" rel="noopener noreferrer">Open official guidance <ExternalLink size={15} /></a></div></header>
    <nav className="company-v1-nav" aria-label={`${guide.company} guide sections`}><div className="page-width"><a href="#current-guidance">Current guidance</a><a href="#preparation">Practice</a><a href="#levels">Levels</a><a href="#experiences">Experiences</a><a href="#recruiter-checks">Recruiter checks</a><a href="#sources">Sources</a></div></nav>
    <div className="page-width company-v1-layout">
      <section id="current-guidance"><h2>Current guidance and evidence limits</h2><p>Each statement below carries its own source, applicability, verification date, review date, and confidence. Missing process detail stays missing.</p><div className="company-v1-claims">{guide.claims.map((item) => { const source = sources.get(item.sourceId); return <article id={`claim-${item.id}`} key={item.id}><header><span className={`company-v1-evidence ${item.sourceClass === "official" ? "official" : "recommendation"}`}>{item.displayLabel}</span><span className="company-v1-relevance">{item.section.replace("-", " ")}</span></header><h3>{item.text}</h3><dl><div><dt>Applies to</dt><dd>{item.applicability}</dd></div><div><dt>Verified</dt><dd>{item.verifiedAt}</dd></div><div><dt>Review by</dt><dd>{item.reviewBy}</dd></div><div><dt>Confidence</dt><dd>{item.confidence}{item.mayVary ? " · May vary" : ""}</dd></div></dl><p>{item.editorialNote}</p>{source && <a href={source.url} target="_blank" rel="noopener noreferrer">Open supporting source <ExternalLink size={14} /></a>}</article>; })}</div><div className="company-v1-boundary"><ShieldCheck size={18} /><div><strong>Evidence boundary</strong><p>Official guidance, approved candidate reports, Engineering Foundry recommendations, and private recruiter-confirmed details remain separate. A report never becomes company policy.</p></div></div></section>
      <section id="preparation"><h2>Choose a transferable practice action</h2><p>These are qualitative Engineering Foundry recommendations, not claimed interview weights or predicted questions.</p><div className="company-v1-domains">{guide.domains.map((domain) => <article key={domain.id}><div><span className={`company-v1-evidence ${domain.evidence}`}>{labels[domain.evidence]}</span><span className="company-v1-relevance">{domain.relevance.replace("-", " ")}</span></div><h3>{domain.title}</h3><p>{domain.summary}</p><Link href={domain.href} className="text-link">{domain.actionLabel} <ArrowRight size={14} /></Link></article>)}</div></section>
      <section id="levels"><h2>Level expectations</h2><p>Engineering Foundry uses Entry, Mid, Senior, and Staff+ as preparation bands. The active job posting and recruiter-confirmed scope are authoritative for this application.</p><div className="company-v1-levels">{guide.levelMappings.map((mapping) => <article key={mapping.level}><h3>{mapping.level}</h3><strong>{mapping.companyTitles}</strong><p>{mapping.caveat}</p>{mapping.level === "Staff+" && <ul>{guide.staffPlus.map((item) => <li key={item}>{item}</li>)}</ul>}</article>)}</div></section>
      <section><h2>Behavioral preparation and sequence</h2><div className="company-v1-two-up"><article><span className="company-v1-evidence recommendation">Engineering Foundry recommendation</span><h3>Prepare truthful stories</h3><p>Develop stories locally. Public company guides never copy private story content.</p><ul>{guide.behavioralThemes.map((theme) => <li key={theme}>{theme}</li>)}</ul><Link className="button button-secondary" href="/behavioral/practice">Practice behavioral prompts</Link></article><article><span className="company-v1-evidence recommendation">Engineering Foundry recommendation</span><h3>Preparation sequence</h3><ol>{guide.recommendations.map((item) => <li key={item}>{item}</li>)}</ol><Link className="button" href="/interview-tips">Open interview execution guide</Link></article></div></section>
      <section id="experiences"><h2>Related Interview Experiences</h2><p>Only approved contributor reports with publication consent appear here. They describe one person’s experience and may not reflect the current process.</p>{experienceAvailability === "unavailable" ? <div className="empty-inline" role="alert"><strong>Reviewed reports are temporarily unavailable</strong><span>We could not verify a complete company report list right now. Try again later.</span></div> : experienceAvailability === "unconfigured" ? <div className="empty-inline" role="status"><strong>Reviewed reports are unavailable in this environment</strong><span>The public publication service is not configured here, so this guide cannot make a completeness claim.</span></div> : experiences.length ? <div className="company-v1-experiences">{experiences.map((experience) => <article key={experience.id}><span className="company-v1-evidence candidate">Candidate-reported · approved</span><h3>{experience.role_title}{experience.role_level ? ` · ${experience.role_level}` : ""}</h3><p>{experience.summary}</p><small>{[experience.region, experience.interview_date?.slice(0, 7)].filter(Boolean).join(" · ") || "Applicability not supplied"}</small></article>)}</div> : <div className="empty-inline"><strong>No approved public experiences yet</strong><span>This is an honest empty state; no demo reports are shown.</span><Link href={`/interview-experiences/${guide.slug}`} className="text-link">Browse interview experiences <ArrowRight size={14} /></Link></div>}</section>
      <section id="recruiter-checks"><h2>Confirm before you rehearse</h2><p>Recruiter or interview instructions for this application override generic public expectations and remain private to the application.</p><div className="company-v1-confirm"><div><h3>Ask recruiting</h3><ul>{guide.recruiterQuestions.map((question) => <li key={question}>{question}</li>)}</ul></div><div><span className="company-v1-evidence candidate">Candidate-confirmed private</span><h3>{accountPlatformAvailable ? "Use the application planner" : "Private planning is unavailable here"}</h3><p>{accountPlatformAvailable ? "Record only the confirmed round sequence for this application. It changes this application’s plan without rewriting the public company guide." : "This environment has no configured account workspace. Use the public execution guide now and keep recruiter-confirmed details in your own private notes."}</p><Link className="button button-secondary" href={accountPlatformAvailable ? "/interview-playbook" : "/interview-tips"}>{accountPlatformAvailable ? "Open private application planner" : "Open public execution guide"}</Link></div></div></section>
      <section id="sources"><h2>Sources, freshness, and limits</h2><p>Re-check the active job description and recruiter instructions before acting on this guide. Source publication dates are shown as unavailable when the publisher does not provide one.</p><div className="company-v1-sources">{guide.sources.map((source) => <article key={source.id}><span className={`company-v1-evidence ${source.kind}`}>{labels[source.kind]}</span><h3>{source.title}</h3><dl><div><dt>Published</dt><dd>{source.publishedAt ?? "Not stated"}</dd></div><div><dt>Verified</dt><dd>{source.verifiedAt}</dd></div><div><dt>Confidence</dt><dd>{source.confidence}</dd></div><div><dt>Volatility</dt><dd>{source.volatility}</dd></div></dl><p>Applies to: {source.applicability}</p><a href={source.url} target="_blank" rel="noopener noreferrer">Open source <ExternalLink size={14} /></a></article>)}</div></section>
    </div>
  </main>;
}
