import Link from "next/link";
import { ArrowRight, ExternalLink, ShieldCheck } from "lucide-react";
import type { CompanyGuideV1 } from "@/data/company-guides/v1";
import type { CompanyInterviewGuide } from "@/data/company-guides/types";
import type { PublicInterviewExperienceAvailability } from "@/lib/supabase/public";
import { CompanyGuideWorkspace } from "./company-guide-workspace";

export type CompanyGuidePublicExperience = { id: string; role_title: string; role_level: string | null; region: string | null; interview_date: string | null; summary: string; interview_experience_rounds: { round_type: string; topic_labels: string[] }[] | null };

const labels = { official: "Official source", candidate: "Candidate-reported", recommendation: "Engineering Foundry recommendation" } as const;

export function CompanyGuideV1Workspace({ experienceAvailability, guide, experiences, matureGuide }: { experienceAvailability: PublicInterviewExperienceAvailability; guide: CompanyGuideV1; experiences: CompanyGuidePublicExperience[]; matureGuide?: CompanyInterviewGuide }) {
  return <main className="company-v1">
    <header className="company-v1-hero"><div className="page-width"><Link href="/companies" className="text-link">All company guides</Link><h1>{guide.company} engineering interview guide</h1><p>{guide.overview}</p><div className="company-v1-meta"><span>Source verification: {guide.verifiedAt}</span><span>Processes vary by role, team, location, and time.</span></div><a className="button button-secondary" href={guide.sources[0].url} target="_blank" rel="noopener noreferrer">Open official guidance <ExternalLink size={15} /></a></div></header>
    <nav className="company-v1-nav" aria-label={`${guide.company} guide sections`}><div className="page-width"><a href="#p04-process">Process</a><a href="#p04-prepare">Preparation domains</a><a href="#p04-levels">Levels</a><a href="#p04-experiences">Experiences</a>{matureGuide && <a href="#mature-guide">Detailed guide</a>}<a href="#p04-sources">Sources</a></div></nav>
    <div className="page-width company-v1-layout">
      <section id="p04-process"><h2>Overview and interview process</h2><p>{guide.process}</p><div className="company-v1-boundary"><ShieldCheck size={18} /><div><strong>Evidence boundary</strong><p>Official information, contributor reports, and Engineering Foundry recommendations are kept distinct. No report becomes company policy.</p></div></div></section>
      <section id="p04-prepare"><h2>Preparation domains</h2><p>Choose the next canonical practice route. These are qualitative preparation recommendations, not claimed interview weighting.</p><div className="company-v1-domains">{guide.domains.map((domain) => <article key={domain.id}><div><span className={`company-v1-evidence ${domain.evidence}`}>{labels[domain.evidence]}</span><span className="company-v1-relevance">{domain.relevance.replace("-", " ")}</span></div><h3>{domain.title}</h3><p>{domain.summary}</p><Link href={domain.href} className="text-link">{domain.actionLabel} <ArrowRight size={14} /></Link></article>)}</div></section>
      <section id="p04-levels"><h2>Level expectations</h2><p>Engineering Foundry uses Entry, Mid, Senior, and Staff+ for preparation. Company titles are contextual, not an exact equivalence between companies.</p><div className="company-v1-levels">{guide.levelMappings.map((mapping) => <article key={mapping.level}><h3>{mapping.level}</h3><strong>{mapping.companyTitles}</strong><p>{mapping.caveat}</p>{mapping.level === "Staff+" && <ul>{guide.staffPlus.map((item) => <li key={item}>{item}</li>)}</ul>}</article>)}</div></section>
      <section><h2>Behavioral / values and next actions</h2><div className="company-v1-two-up"><article><h3>Prepare truthful stories</h3><p>Use the private Behavioral workspace; public company guides never copy your stories.</p><ul>{guide.behavioralThemes.map((theme) => <li key={theme}>{theme}</li>)}</ul><Link className="button button-secondary" href="/behavioral/workspace">Open story workspace</Link></article><article><h3>Recommended preparation sequence</h3><ol>{guide.recommendations.map((item) => <li key={item}>{item}</li>)}</ol><Link className="button" href="/interview-playbook">Open Interview Playbook</Link></article></div></section>
      <section id="p04-experiences"><h2>Related Interview Experiences</h2><p>Only approved contributor reports with publication consent appear here. They describe one experience and may not reflect the current process.</p>{experienceAvailability === "unavailable" ? <div className="empty-inline" role="alert"><strong>Reviewed reports are temporarily unavailable</strong><span>We could not verify a complete company report list right now. Try again later.</span></div> : experienceAvailability === "unconfigured" ? <div className="empty-inline" role="status"><strong>Reviewed reports are unavailable in this environment</strong><span>The public publication service is not configured here, so this guide cannot make a completeness claim.</span></div> : experiences.length ? <div className="company-v1-experiences">{experiences.map((experience) => <article key={experience.id}><h3>{experience.role_title}{experience.role_level ? ` · ${experience.role_level}` : ""}</h3><p>{experience.summary}</p><small>{[experience.region, experience.interview_date?.slice(0, 7)].filter(Boolean).join(" · ")}</small></article>)}</div> : <div className="empty-inline"><strong>No approved public experiences yet</strong><span>This is an honest empty state; no demo reports are shown.</span><Link href={`/interview-experiences/${guide.slug}`} className="text-link">Browse interview experiences <ArrowRight size={14} /></Link></div>}</section>
      {matureGuide && <section id="mature-guide"><h2>Detailed company-specific research</h2><p>Open the established {guide.company} research only when you need round detail, level-specific planning, or deeper source context. The normalized guide above remains the page-level orientation.</p><details className="company-detail company-v1-mature-detail"><summary><span><strong>Open detailed {guide.company} guide</strong><small>Existing level-specific process, practice, behavioral, and source material</small></span></summary><div><CompanyGuideWorkspace guide={matureGuide} embedded /></div></details></section>}
      <section id="p04-sources"><h2>Sources, freshness, and limits</h2><p>Last source verification: {guide.verifiedAt}. Re-check the job description and recruiter instructions before acting on this guide.</p><div className="company-v1-sources">{guide.sources.map((source) => <article key={source.id}><span className={`company-v1-evidence ${source.kind}`}>{labels[source.kind]}</span><h3>{source.title}</h3><p>Confidence: {source.confidence}. Applies to: {source.applicability}</p><a href={source.url} target="_blank" rel="noopener noreferrer">Open source <ExternalLink size={14} /></a></article>)}</div></section>
    </div>
  </main>;
}
