"use client";

import { AlertTriangle, ArrowLeftRight, Braces, ChevronDown, Circle, ExternalLink, Lightbulb, Network, RotateCcw, ShieldCheck } from "lucide-react";
import Link from "next/link";
import type { RoadmapProblem } from "@/data/dsa/level-roadmaps";
import type { RoadmapProblemStatus } from "@/data/dsa/roadmap-planning";
import { track } from "@/lib/analytics";
import { QuickDsaStatusControl } from "@/features/dsa/progress/quick-progress-actions";

const classificationLabels = { learn: "Learn", core: "Core", practice: "Practice", stretch: "Stretch" } as const;
const statusLabels: Record<RoadmapProblemStatus, string> = { "not-started": "Not Started", attempted: "Attempted", solved: "Solved", review: "Review" };

export function RoadmapProblemRow({ problem, hidePattern = false, status = "not-started", signedIn = false }: { problem: RoadmapProblem; hidePattern?: boolean; status?: RoadmapProblemStatus; signedIn?: boolean }) {
  return <details className="dsa-roadmap-problem-row" onToggle={(event) => { if (event.currentTarget.open) track("roadmap_problem_opened", { problem_id: problem.id, classification: problem.classification }); }}>
    <summary className="dsa-roadmap-problem-summary">
      <span className={`dsa-roadmap-problem-state ${status}`} aria-label={`${problem.title} status: ${statusLabels[status]}`} title="Roadmap status is read from account-backed progress when available"><Circle size={13} aria-hidden="true" /><small>{statusLabels[status]}</small></span>
      <span className="dsa-roadmap-problem-title"><strong>{problem.title}</strong>{!hidePattern && <small>{problem.pattern}</small>}</span>
      <span className={`dsa-roadmap-difficulty ${problem.difficulty?.toLowerCase()}`}>{problem.difficulty}</span>
      <span className={`dsa-roadmap-classification ${problem.classification}`}>{classificationLabels[problem.classification]}</span>
      <a href={problem.url} target="_blank" rel="noopener noreferrer" aria-label={`Open ${problem.title} on LeetCode (opens in a new tab)`} onClick={(event) => { event.stopPropagation(); track("dsa_question_clicked", { problem_id: problem.id, source: problem.source ?? "other" }); }}><ExternalLink size={15} aria-hidden="true" /></a>
      <ChevronDown className="dsa-roadmap-problem-chevron" size={16} aria-hidden="true" />
    </summary>
    <div className="dsa-roadmap-problem-details">
      <div className="dsa-roadmap-progress-actions"><Link href={`/dsa/questions/${problem.id}`}>Open practice record</Link>{signedIn && <QuickDsaStatusControl questionId={problem.id} status={status} />}</div>
      {problem.whyItMatters && <section><strong className="dsa-roadmap-detail-label">Why this problem</strong><p>{problem.whyItMatters}</p></section>}
      {problem.levelRationale && <section className="dsa-roadmap-level-rationale"><strong className="dsa-roadmap-detail-label">{problem.levelRationaleLabel ?? "Why this is SDE II"}</strong><p>{problem.levelRationale}</p></section>}
      {!!problem.invariants?.length && <section className="dsa-roadmap-invariant"><strong className="dsa-roadmap-detail-label"><ShieldCheck size={14} aria-hidden="true" />Invariant</strong><ul>{problem.invariants.map((invariant) => <li key={invariant}>{invariant}</li>)}</ul></section>}
      {!!problem.skills?.length && <section><strong className="dsa-roadmap-detail-label">Skills tested</strong><div className="dsa-roadmap-problem-skills">{problem.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></section>}
      {!!problem.alternativeApproaches?.length && <details className="dsa-roadmap-problem-disclosure dsa-roadmap-alternatives"><summary className="dsa-roadmap-problem-disclosure-summary"><ArrowLeftRight size={14} aria-hidden="true" />{problem.alternativeLabel ?? "Alternative approaches"} <ChevronDown size={14} aria-hidden="true" /></summary><div className="dsa-roadmap-comparison-table"><table><caption>{problem.title} approach comparison</caption><thead><tr><th>Approach</th><th>Time</th><th>Space</th><th>Use when</th></tr></thead><tbody>{problem.alternativeApproaches.map((approach) => <tr key={approach.title}><td>{approach.title}</td><td>{approach.time}</td><td>{approach.space}</td><td>{approach.whenUseful}</td></tr>)}</tbody></table></div></details>}
      {!!problem.followUps?.length && <details className="dsa-roadmap-problem-disclosure"><summary className="dsa-roadmap-problem-disclosure-summary"><RotateCcw size={14} aria-hidden="true" />Interview follow-ups <ChevronDown size={14} aria-hidden="true" /></summary><ul>{problem.followUps.map((followUp) => <li key={followUp}>{followUp}</li>)}</ul></details>}
      {!!problem.categorizedFollowUps?.length && <details className="dsa-roadmap-problem-disclosure dsa-roadmap-senior-followups"><summary className="dsa-roadmap-problem-disclosure-summary"><RotateCcw size={14} aria-hidden="true" />Senior follow-ups <span>{problem.categorizedFollowUps.length}</span><ChevronDown size={14} aria-hidden="true" /></summary><div>{problem.categorizedFollowUps.map((followUp) => <article key={`${followUp.category}-${followUp.prompt}`}><span className={`dsa-roadmap-followup-category ${followUp.category}`}>{followUp.category === "concurrency" ? "Concurrency Follow-up" : followUp.category}</span><p>{followUp.prompt}</p></article>)}</div></details>}
      {problem.apiContract && <details className="dsa-roadmap-problem-disclosure dsa-roadmap-api-contract"><summary className="dsa-roadmap-problem-disclosure-summary"><Braces size={14} aria-hidden="true" />API Contract <ChevronDown size={14} aria-hidden="true" /></summary><div><section><strong className="dsa-roadmap-detail-label">Operations</strong><ul>{problem.apiContract.operations.map((item) => <li key={item}>{item}</li>)}</ul></section><section><strong className="dsa-roadmap-detail-label">Complexity goals</strong><ul>{problem.apiContract.complexityGoals.map((item) => <li key={item}>{item}</li>)}</ul></section><section><strong className="dsa-roadmap-detail-label">Assumptions</strong><ul>{problem.apiContract.assumptions.map((item) => <li key={item}>{item}</li>)}</ul></section></div></details>}
      {!!problem.failureChecks?.length && <details className="dsa-roadmap-problem-disclosure dsa-roadmap-failure-checks"><summary className="dsa-roadmap-problem-disclosure-summary"><AlertTriangle size={14} aria-hidden="true" />What can go wrong? <ChevronDown size={14} aria-hidden="true" /></summary><ul>{problem.failureChecks.map((failure) => <li key={failure}>{failure}</li>)}</ul></details>}
      {problem.designBridge && <details className="dsa-roadmap-problem-disclosure dsa-roadmap-design-bridge"><summary className="dsa-roadmap-problem-disclosure-summary"><Network size={14} aria-hidden="true" />From Algorithm to Design <ChevronDown size={14} aria-hidden="true" /></summary><strong className="dsa-roadmap-detail-label">{problem.designBridge.title}</strong><ul>{problem.designBridge.points.map((point) => <li key={point}>{point}</li>)}</ul>{problem.designBridge.href && <Link href={problem.designBridge.href}>{problem.designBridge.linkLabel ?? "Open related System Design lesson"} <ExternalLink size={13} aria-hidden="true" /></Link>}</details>}
      {!!problem.hints?.length && <details className="dsa-roadmap-problem-disclosure" onToggle={(event) => { if (event.currentTarget.open) track("roadmap_hint_revealed", { problem_id: problem.id }); }}><summary className="dsa-roadmap-problem-disclosure-summary"><Lightbulb size={14} aria-hidden="true" />Staged hints <ChevronDown size={14} aria-hidden="true" /></summary><p>Spend focused time first. Use the smallest hint that gets you moving, then finish the solution yourself.</p><ol>{problem.hints.map((hint, index) => <li key={hint}><strong>Hint {index + 1}</strong>{hint}</li>)}</ol></details>}
    </div>
  </details>;
}
