import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Plus } from "lucide-react";
import { notFound } from "next/navigation";
import { AccountUnavailable } from "@/components/account-unavailable";
import { ConfirmAction } from "@/features/applications/confirm-action";
import { deleteAnswerAction, deleteQuestionAction, linkStoryAction, unlinkStoryAction } from "@/features/behavioral/actions";
import { isAccountPlatformAvailable } from "@/lib/account-platform";
import { requireMemberProfile } from "@/lib/auth/guards";
import { answerMatchesQuestion, getBehavioralWorkspaceData, linkMatchesQuestion, preparationStatus, preparationStatusLabel } from "@/lib/behavioral/queries";
import { storyReadiness } from "@/lib/behavioral/readiness";
import { BehavioralQuestionGuidance } from "@/features/behavioral/preparation-guidance";

export const metadata: Metadata = { title: "Behavioral question", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

export default async function BehavioralQuestionPage({ params, searchParams }: { params: Promise<{ questionId: string }>; searchParams: Promise<{ application?: string; company?: string }> }) {
  if (!isAccountPlatformAvailable()) return <AccountUnavailable />;
  const { questionId } = await params; const context = await searchParams; await requireMemberProfile(`/behavioral/questions/${questionId}`); const data = await getBehavioralWorkspaceData(); const question = data.questions.find((item) => item.id === questionId); if (!question) notFound(); const application = data.applications.find((item) => item.id === context.application); const answerContext = new URLSearchParams(); if (application) answerContext.set("application", application.id); if (application?.company_slug ?? context.company) answerContext.set("company", application?.company_slug ?? context.company ?? ""); const answerSuffix = answerContext.size ? `?${answerContext}` : "";
  const links = data.links.filter((link) => linkMatchesQuestion(link, question)); const answers = data.answers.filter((answer) => answerMatchesQuestion(answer, question)).sort((a, b) => Number(b.is_primary) - Number(a.is_primary)); const availableStories = data.stories.filter((story) => !links.some((link) => link.story_id === story.id)); const status = preparationStatus(question, data);
  return <div className="behavioral-workspace"><div className="page-width behavioral-detail-width"><Link className="behavioral-back" href={`/behavioral/questions${answerSuffix}`}><ArrowLeft size={14} />All questions</Link>
    <header className="behavioral-detail-header"><div className="behavioral-card-meta"><span>{question.category}</span><span>{question.source === "curated" ? "Engineering Foundry curated" : "Your private question"}</span>{question.companySlug && <span>{question.companySlug.replaceAll("-", " ")}</span>}{application && <span>{application.company_name} · {application.role_title}</span>}</div><h1>{question.prompt}</h1>{question.description && <p>{question.description}</p>}<div className="behavioral-detail-actions"><span className={`behavioral-status status-${status.toLowerCase().replaceAll(" ", "-")}`}>{preparationStatusLabel(status)}</span><Link className="button button-sm" href={`/behavioral/questions/${question.id}/answers/new${answerSuffix}`}><Plus size={15} />Draft answer</Link>{question.custom && <Link className="button button-secondary button-sm" href={`/behavioral/questions/${question.id}/edit`}>Edit question</Link>}{question.custom && <ConfirmAction action={deleteQuestionAction.bind(null, question.id)} label="Delete question" />}</div></header>
    {question.curated && <section className="behavioral-guidance"><div><h2>What this question is probing</h2><ul>{question.curated.signals.map((signal) => <li key={signal}>{signal}</li>)}</ul></div><div><h2>Useful follow-ups</h2><ul>{question.curated.followUps.map((followUp) => <li key={followUp}>{followUp}</li>)}</ul></div><div><h2>Common mistakes</h2><ul>{question.curated.commonMistakes.map((mistake) => <li key={mistake}>{mistake}</li>)}</ul></div></section>}
    <BehavioralQuestionGuidance question={question} companySlug={application?.company_slug ?? context.company ?? question.companySlug} />
    <section className="behavioral-detail-section"><div className="behavioral-section-heading"><div><h2>Linked stories</h2><p>One story can support several questions; this list stays independent of company-specific framing.</p></div>{availableStories.length ? <form action={linkStoryAction.bind(null, question.id)} className="behavioral-inline-form"><label className="sr-only" htmlFor="link-story">Story to link</label><select id="link-story" name="story_id" required defaultValue=""><option value="" disabled>Choose a story</option>{availableStories.map((story) => <option key={story.id} value={story.id}>{story.title} · {storyReadiness(story)}</option>)}</select><button className="button button-secondary button-sm">Link story</button></form> : <Link className="button button-secondary button-sm" href="/behavioral/stories/new">Create a story</Link>}</div>{links.length ? <div className="behavioral-linked-list">{links.map((link) => { const story = data.stories.find((item) => item.id === link.story_id); if (!story) return null; const primary = answers.some((answer) => answer.story_id === story.id && answer.is_primary); const usedByPreparation = answers.some((answer) => answer.story_id === story.id); return <article key={link.id}><div><Link href={`/behavioral/stories/${story.id}`}>{story.title}{primary && <span className="behavioral-primary-label">Primary</span>}</Link><span>{storyReadiness(story)}{story.company_or_context ? ` · ${story.company_or_context}` : ""}</span></div>{usedByPreparation ? <span className="behavioral-link-lock">Used by preparation</span> : <form action={unlinkStoryAction.bind(null, link.id, question.id)}><button className="tracker-danger-link">Unlink</button></form>}</article>; })}</div> : <p className="behavioral-empty-inline">No story linked yet. Link one story that gives specific evidence for this prompt.</p>}</section>
    <section className="behavioral-detail-section"><div className="behavioral-section-heading"><div><h2>Answer preparation</h2><p>Save framing and emphasis without copying the underlying STAR story.</p></div><Link className="button button-secondary button-sm" href={`/behavioral/questions/${question.id}/answers/new${answerSuffix}`}><Plus size={15} />Create variant</Link></div>{answers.length ? <div className="behavioral-answer-list">{answers.map((answer) => { const answerApplication = data.applications.find((item) => item.id === answer.application_id); return <article key={answer.id}><header><div><h3>{answer.title}{answer.is_primary && <span className="behavioral-primary-label">Primary story</span>}</h3><span>{answer.status}{answerApplication ? ` · ${answerApplication.company_name} — ${answerApplication.role_title}` : answer.company_slug ? ` · ${answer.company_slug.replaceAll("-", " ")}` : " · General"}</span></div><div className="behavioral-answer-actions"><Link href={`/behavioral/questions/${question.id}/answers/${answer.id}/edit`}>Edit</Link><ConfirmAction action={deleteAnswerAction.bind(null, answer.id, question.id)} label="Delete" /></div></header>{answer.opening_framing && <p><strong>Opening:</strong> {answer.opening_framing}</p>}{answer.details_to_emphasize && <p><strong>Emphasize:</strong> {answer.details_to_emphasize}</p>}{answer.details_to_avoid && <p><strong>Avoid:</strong> {answer.details_to_avoid}</p>}{answer.notes && <p><strong>Notes:</strong> {answer.notes}</p>}{answer.answer_text && <details className="behavioral-answer-draft"><summary>Rehearsal draft — concise or standard</summary><p>Use a concise presentation (roughly 45–90 seconds) or a standard one (roughly 90–180 seconds) without changing the source facts.</p><p>{answer.answer_text}</p></details>}{answer.story_id && <Link href={`/behavioral/stories/${answer.story_id}`}>Open source story</Link>}</article>; })}</div> : <p className="behavioral-empty-inline">No preparation yet. Choose a story and add only the framing you need for this prompt.</p>}</section>
    {question.custom?.notes && <section className="behavioral-private-notes"><span>Private notes</span><p>{question.custom.notes}</p></section>}
  </div></div>;
}
