import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  PINNED_NODE_VERSION,
  PINNED_NPM_VERSION,
  PINNED_SUPABASE_CLI_VERSION,
  PRODUCTION_BUILD_COMMAND,
  PRODUCTION_BUILD_DESCRIPTION,
  RELEASE_QUALIFICATION_COMMANDS,
} from "./release-verification-manifest.mjs";

export const RELEASE_JSON_PATH = "docs/releases/v1-release-candidate.json";
export const RELEASE_MARKDOWN_PATH = "docs/releases/v1-release-candidate.md";
export const RELEASE_RECORD_PATHS = [RELEASE_JSON_PATH, RELEASE_MARKDOWN_PATH];

function git(args, options = {}) {
  return execFileSync("git", args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], ...options }).trim();
}

function fullCommit(value) {
  return git(["rev-parse", "--verify", `${value}^{commit}`]);
}

function migrationState() {
  const migrations = readdirSync("supabase/migrations").filter((name) => name.endsWith(".sql")).sort();
  assert.ok(migrations.length > 0, "At least one migration is required.");
  return { migration_count: migrations.length, final_migration_filename: migrations.at(-1) };
}

function workingTreePaths() {
  const output = git(["status", "--porcelain=v1", "--untracked-files=all"]);
  if (!output) return [];
  return output.split("\n").map((line) => {
    const name = line.slice(3);
    return name.includes(" -> ") ? name.split(" -> ").at(-1) : name;
  });
}

export function renderReleaseMarkdown(record) {
  return `# ${record.release_name}

> Generated from \`${RELEASE_JSON_PATH}\`. Do not edit this file directly.

## Candidate identity

| Field | Value |
| --- | --- |
| Record schema/version | \`${record.schema_version}/${record.record_version}\` |
| Base SHA | \`${record.base_sha}\` |
| Candidate SHA | \`${record.candidate_sha}\` |
| Candidate branch | \`${record.candidate_branch}\` |
| Qualified at (UTC) | \`${record.qualified_at_utc}\` |
| Production status | \`${record.production_status}\` |

The candidate SHA is the immediately preceding code commit. This metadata commit may change only this Markdown file and its JSON source record.

## Pinned release toolchain

| Tool | Version |
| --- | --- |
| Node.js | \`${record.toolchain.node}\` |
| npm | \`${record.toolchain.npm}\` |
| Supabase CLI | \`${record.toolchain.supabase_cli}\` |

The canonical build is **${record.build.description}**: \`${record.build.command}\` (framework command \`${record.build.framework_command}\`).

## Repository-derived database state

- Migration count: \`${record.database.migration_count}\`
- Final migration: \`${record.database.final_migration_filename}\`

## Qualification commands

${record.qualification_commands.map((command) => `- \`${command}\``).join("\n")}

## Hosted-production boundary

${record.hosted_owner_gates_statement}

This record does not claim a deployment, hosted Supabase qualification, production account enablement, production analytics enablement, or completion of any external owner gate.
`;
}

function assertAllowedWorkingTree() {
  const unexpected = workingTreePaths().filter((name) => !RELEASE_RECORD_PATHS.includes(name));
  assert.deepEqual(unexpected, [], `Only release-record files may be dirty: ${unexpected.join(", ")}`);
}

export function validateReleaseRecord({ allowAbsent = true } = {}) {
  const jsonExists = existsSync(RELEASE_JSON_PATH);
  const markdownExists = existsSync(RELEASE_MARKDOWN_PATH);
  assert.equal(jsonExists, markdownExists, "Release-record JSON and Markdown must either both exist or both be absent.");
  if (!jsonExists) {
    assert.ok(allowAbsent, "The release record is required.");
    return { status: "ABSENT" };
  }

  const record = JSON.parse(readFileSync(RELEASE_JSON_PATH, "utf8"));
  assert.equal(record.schema_version, 1);
  assert.equal(record.record_version, 1);
  assert.equal(record.release_name, "Engineering Foundry v1 release candidate");
  assert.match(record.base_sha, /^[0-9a-f]{40}$/);
  assert.match(record.candidate_sha, /^[0-9a-f]{40}$/);
  assert.equal(fullCommit(record.base_sha), record.base_sha, "Recorded base SHA is not a full commit SHA.");
  assert.equal(fullCommit(record.candidate_sha), record.candidate_sha, "Recorded candidate SHA is not a full commit SHA.");
  execFileSync("git", ["merge-base", "--is-ancestor", record.candidate_sha, "HEAD"]);
  execFileSync("git", ["merge-base", "--is-ancestor", record.base_sha, record.candidate_sha]);

  const head = fullCommit("HEAD");
  if (head !== record.candidate_sha) {
    assert.equal(fullCommit("HEAD^"), record.candidate_sha, "The metadata commit must immediately follow the candidate commit.");
  }
  const committedAfterCandidate = git(["diff", "--name-only", `${record.candidate_sha}..HEAD`]).split("\n").filter(Boolean);
  assert.ok(committedAfterCandidate.every((name) => RELEASE_RECORD_PATHS.includes(name)), "A non-release-record file changed after the candidate commit.");
  if (head !== record.candidate_sha) {
    assert.deepEqual([...committedAfterCandidate].sort(), [...RELEASE_RECORD_PATHS].sort(), "The metadata commit must contain exactly both release-record files.");
  }
  assertAllowedWorkingTree();

  assert.equal(record.candidate_branch, "feat/p0-final-launch-readiness");
  assert.match(record.qualified_at_utc, /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/);
  assert.equal(record.production_status, "not_deployed_or_hosted_qualified");
  assert.equal(record.hosted_owner_gates_complete, false);
  assert.match(record.hosted_owner_gates_statement, /remain incomplete/i);

  const packageJson = JSON.parse(readFileSync("package.json", "utf8"));
  assert.equal(readFileSync(".nvmrc", "utf8").trim(), PINNED_NODE_VERSION);
  assert.equal(packageJson.engines.node, PINNED_NODE_VERSION);
  assert.equal(packageJson.packageManager, `npm@${PINNED_NPM_VERSION}`);
  assert.equal(packageJson.devDependencies.supabase, PINNED_SUPABASE_CLI_VERSION);
  assert.deepEqual(record.toolchain, { node: PINNED_NODE_VERSION, npm: PINNED_NPM_VERSION, supabase_cli: PINNED_SUPABASE_CLI_VERSION });
  assert.equal(packageJson.scripts.build, PRODUCTION_BUILD_COMMAND);
  assert.deepEqual(record.build, { command: "npm run build", framework_command: PRODUCTION_BUILD_COMMAND, description: PRODUCTION_BUILD_DESCRIPTION });
  assert.deepEqual(record.database, migrationState());
  assert.deepEqual(record.qualification_commands, RELEASE_QUALIFICATION_COMMANDS);
  assert.equal(readFileSync(RELEASE_MARKDOWN_PATH, "utf8"), renderReleaseMarkdown(record), "Generated Markdown does not match the JSON release record.");
  return { status: "VALID", record };
}

function generateReleaseRecord(candidateArgument, baseArgument) {
  assertAllowedWorkingTree();
  const candidateSha = fullCommit(candidateArgument || "HEAD");
  assert.equal(candidateSha, fullCommit("HEAD"), "Generate the release record only while HEAD is the candidate commit.");
  const baseSha = fullCommit(baseArgument || git(["merge-base", "main", candidateSha]));
  const record = {
    schema_version: 1,
    record_version: 1,
    release_name: "Engineering Foundry v1 release candidate",
    base_sha: baseSha,
    candidate_sha: candidateSha,
    candidate_branch: git(["branch", "--show-current"]),
    qualified_at_utc: new Date().toISOString().replace(/\.\d{3}Z$/, "Z"),
    toolchain: { node: PINNED_NODE_VERSION, npm: PINNED_NPM_VERSION, supabase_cli: PINNED_SUPABASE_CLI_VERSION },
    database: migrationState(),
    build: { command: "npm run build", framework_command: PRODUCTION_BUILD_COMMAND, description: PRODUCTION_BUILD_DESCRIPTION },
    qualification_commands: RELEASE_QUALIFICATION_COMMANDS,
    production_status: "not_deployed_or_hosted_qualified",
    hosted_owner_gates_complete: false,
    hosted_owner_gates_statement: "Hosted owner gates remain incomplete and require separate, dated evidence from the deployment owner.",
  };
  writeFileSync(RELEASE_JSON_PATH, `${JSON.stringify(record, null, 2)}\n`);
  writeFileSync(RELEASE_MARKDOWN_PATH, renderReleaseMarkdown(record));
  validateReleaseRecord({ allowAbsent: false });
  console.log(`Generated and validated release records for candidate ${candidateSha}.`);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const command = process.argv[2] || "validate";
  if (command === "validate") {
    const result = validateReleaseRecord({ allowAbsent: true });
    console.log(result.status === "ABSENT" ? "Release record absent; candidate-code state is valid." : `Release record valid for ${result.record.candidate_sha}.`);
  } else if (command === "generate") {
    generateReleaseRecord(process.argv[3], process.argv[4]);
  } else {
    console.error("Use `release:record validate` or `release:record generate [candidate_sha] [base_sha]`.");
    process.exit(2);
  }
}
