import { ProductionEngineeringLesson } from "./shared";

const traceFlow = `sequenceDiagram
  participant C as Client
  participant A as API
  participant O as Order service
  participant P as Payment service
  C->>A: request with trace context
  A->>O: child span and propagated context
  O->>P: child span and propagated context
  P-->>O: payment result
  O-->>A: order result
  A-->>C: response`;

export function ObservabilityLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "observability",
  mentalModel: "Observability is the ability to ask useful questions about a running system from its outputs. Start with user journeys and decisions: a signal earns its ingestion, retention, and on-call cost only when it helps detect, explain, or prevent a meaningful failure.",
  mechanism: ["Name the user outcome, owner, dependency boundary, and acceptable failure.", "Emit structured logs, bounded-cardinality metrics, and trace context at that boundary.", "Route signals through a controlled collection pipeline with redaction, sampling, retention, and access policy.", "Connect symptom alerts to dashboards, traces, logs, and a runbook owned by a team.", "Review unused telemetry and expensive dimensions; reduce cost without removing the signals needed to operate the service."],
  example: { title: "Checkout latency rises only for one payment path", body: "A latency SLI detects the user-visible symptom. A trace identifies the slow payment dependency, a metric shows connection-pool saturation, and correlated logs provide the bounded error detail. No single signal answers every question.", consequence: "Preserve correlation across the checkout boundary and budget telemetry volume by diagnostic value, not by collecting every field forever." },
  tradeoffs: [{ option: "Broad low-cost metrics", chooseWhen: "You need continuous symptom detection and trends.", cost: "Labels must remain bounded and aggregate detail can hide individual requests." }, { option: "Sampled traces", chooseWhen: "Cross-service latency and causality matter.", cost: "Sampling can miss rare cases and full fidelity is expensive." }, { option: "Targeted structured logs", chooseWhen: "Operators need event detail and audit evidence.", cost: "Sensitive data, indexing, and retention require explicit controls." }],
  failure: { failure: "The telemetry pipeline becomes slow during an outage.", impact: "The team loses diagnostic evidence when it is most valuable, while synchronous exporters may worsen the service.", detection: "Exporter queue age, dropped-signal counters, and collector health diverge from application traffic.", mitigation: "Keep export off the request critical path, bound buffers, shed lower-value telemetry, and retain local health signals.", tradeoff: "Bounded pipelines deliberately lose some diagnostic detail under pressure." },
  exercise: ["Choose one user journey and write its latency, availability, and correctness questions.", "Assign the cheapest signal that can answer each question.", "Mark every high-cardinality or sensitive attribute and decide whether to drop, hash, aggregate, or restrict it.", "Name the owning team, retention period, runbook, and monthly cost review."],
  probes: ["Which signal wakes a person, and why?", "What happens when the collector is unavailable?", "How do you stop tenant IDs or request IDs from exploding metric cardinality?", "Who owns the dashboard, runbook, retention, and deletion policy?"],
  levelCalibration: [{ level: "SDE I–II", evidence: "Instrument one request path and distinguish logs, metrics, and traces." }, { level: "Senior", evidence: "Design symptom-led alerts, correlation, failure-safe export, and retention boundaries." }, { level: "Staff", evidence: "Set cross-team semantic conventions, ownership, privacy controls, and a sustainable telemetry cost model." }],
  practice: ["metrics-platform", "distributed-tracing-platform", "log-aggregation"],
  remember: "Begin with an operational question and user outcome. Collect the least expensive, safest set of signals that can answer it, and assign ownership before the incident.",
  note: "Threat model the telemetry plane itself: it may contain identifiers, authorization outcomes, topology, and failure details. Restrict access, redact at collection boundaries, and do not treat an observability backend as a harmless copy of production data.",
}} />; }

export function LogsLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "logs",
  mentalModel: "A log is a timestamped event record, not a stream of prose. Its value comes from stable fields that let an operator filter by service, severity, operation, outcome, trace, and safe business key without exposing secrets or whole payloads.",
  mechanism: ["Define a small event schema with time, severity, body, resource, attributes, and correlation context.", "Emit one event for a meaningful state transition or failure boundary rather than every line of code.", "Redact credentials, tokens, personal data, and unrestricted request bodies before export.", "Buffer and ship asynchronously; index only fields needed for bounded operational queries.", "Apply retention and access by sensitivity, then test that deletion and incident access work."],
  example: { title: "A duplicate payment request", body: "The payment handler logs operation name, safe payment reference, idempotency outcome, dependency status, trace ID, and duration. It does not log the bearer token, card data, or complete request body.", consequence: "Use structured fields for the retry decision and join to a trace; keep financial or personal data outside the general log pipeline." },
  tradeoffs: [{ option: "Structured events", chooseWhen: "Operators need reliable filtering and aggregation.", cost: "Schemas and field governance require maintenance." }, { option: "Full-text messages", chooseWhen: "Human context is useful during early development.", cost: "Parsing is brittle and accidental sensitive data is harder to control." }, { option: "Long retention", chooseWhen: "Audit or slow incident discovery requires it.", cost: "Storage, access risk, and deletion obligations grow." }],
  failure: { failure: "A release logs entire authorization headers on errors.", impact: "Credentials are copied into a widely accessible, long-lived system.", detection: "Secret-scanning rules and sampled pipeline inspection flag token-shaped values.", mitigation: "Redact at instrumentation and collector boundaries, revoke exposed credentials, restrict the dataset, and shorten retention.", tradeoff: "Aggressive redaction can remove debugging detail, so preserve safe identifiers and explicit allowlisted fields." },
  exercise: ["Rewrite an unstructured timeout message as stable fields.", "Classify each field as index, retained body, redacted, or prohibited.", "Choose sampling and retention separately for normal events and security/audit events."],
  probes: ["What does this log let an operator decide?", "Which fields may contain secrets or personal data?", "How do schema changes and timestamp skew affect queries?", "What happens when export buffers fill?"],
  practice: ["log-aggregation", "payment-system"],
  remember: "Log state transitions and outcomes as a safe, stable event schema. Correlation and redaction matter more than log volume.",
}} />; }

export function MetricsLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "metrics",
  mentalModel: "Metrics compress repeated observations into numeric time series. They are excellent for rates, totals, gauges, and distributions, but every label combination creates another series and therefore another unit of memory, storage, and query work.",
  mechanism: ["Choose a user or resource question and the counter, gauge, or histogram that answers it.", "Define units, aggregation, label vocabulary, and reset behavior before emitting data.", "Keep labels bounded; move request IDs, user IDs, and raw error text to traces or logs.", "Aggregate over windows and preserve distributions for latency rather than averaging away the tail.", "Use exemplars or trace links to move from a symptom to a representative request."],
  example: { title: "Measure API latency without a series per user", body: "Record a duration histogram labeled by stable route template, method, region, and outcome class. Do not label it with user ID or raw URL. A trace exemplar can retain request-level context.", consequence: "Bounded labels keep the metric operable while distributions preserve tail behavior needed for an SLI." },
  tradeoffs: [{ option: "More labels", chooseWhen: "A bounded dimension changes diagnosis or ownership.", cost: "Cardinality multiplies ingestion, storage, and query cost." }, { option: "Finer buckets", chooseWhen: "Decision thresholds need more precision.", cost: "More series and still only approximate the distribution." }, { option: "Pre-aggregation", chooseWhen: "High-volume dashboards need predictable queries.", cost: "Lost dimensions cannot be recovered later." }],
  failure: { failure: "A customer ID is added as a metric label.", impact: "Active series count grows with customers, destabilizing ingestion and making queries expensive.", detection: "Series-creation rate and cardinality by label rise sharply after deploy.", mitigation: "Drop the unbounded label, aggregate by a bounded tenant tier, and use a trace or controlled log for individual investigation.", tradeoff: "Operators lose direct per-customer metric filtering." },
  exercise: ["Define one latency histogram and one error counter for an API.", "List every proposed label and prove its value set is bounded.", "Specify which user-visible question each metric answers and the trace/log pivot for deeper diagnosis."],
  probes: ["Why is average latency insufficient?", "Which labels can grow without a fixed bound?", "How does metric aggregation affect multi-region diagnosis?", "What will you stop collecting if telemetry cost doubles?"],
  practice: ["metrics-platform", "event-analytics"],
  remember: "Metrics answer repeated numeric questions cheaply only when labels remain bounded and the aggregation preserves the decision you need to make.",
}} />; }

export function DistributedTracingLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "distributed-tracing",
  mentalModel: "A trace represents one operation as a tree or graph of spans across process boundaries. Trace context supplies correlation; span timing and attributes explain where time and errors accumulated. A trace is evidence about a request, not a complete service-health measure.",
  mechanism: ["Create or accept trace context at the trusted entry boundary.", "Start spans around meaningful client, server, queue, and storage operations.", "Propagate context explicitly across supported carriers and validate untrusted baggage.", "Record status and bounded attributes; avoid payloads, credentials, and uncontrolled identifiers.", "Sample with a stated policy and correlate selected spans to metrics and logs."],
  diagram: { chart: traceFlow, title: "Trace context across an order request", description: "A client request enters an API and passes trace context through order and payment services. Each service records a child span, so the final trace shows the ordered call path and where latency accumulated." },
  example: { title: "Find the slow hop", body: "A checkout trace spends 40 ms in the API, 60 ms in the order service, and 900 ms waiting on payment. The trace directs investigation to the payment dependency; service metrics determine whether the request is representative.", consequence: "Propagate context across every remote boundary and pair traces with aggregate service signals before changing capacity." },
  tradeoffs: [{ option: "Head sampling", chooseWhen: "A cheap decision can be made when the request starts.", cost: "The sampler cannot know the eventual latency or error." }, { option: "Tail sampling", chooseWhen: "Errors and slow traces must be preferentially retained.", cost: "Collectors buffer trace state and require more capacity." }, { option: "Full tracing", chooseWhen: "Traffic is low and diagnostic value exceeds cost.", cost: "Storage, network, and sensitive attribute exposure grow with volume." }],
  failure: { failure: "A queue consumer starts a new unrelated trace.", impact: "The request-to-async-work path is broken and latency attribution stops at the broker.", detection: "Traces end at publish spans while consumers show orphan roots for the same operation.", mitigation: "Propagate or link the supported context in message metadata and test the producer/consumer boundary.", tradeoff: "Context increases message metadata and long delays may make parent-child semantics misleading, so span links can be preferable." },
  exercise: ["Draw spans for one synchronous call and one queued continuation.", "Mark where context enters, propagates, is validated, and may be sampled.", "Choose five safe span attributes and one attribute that must remain out of telemetry."],
  probes: ["Where can trace context be lost?", "How do retries appear in the trace?", "When would you use a link instead of a child span?", "How does sampling bias an incident investigation?"],
  practice: ["distributed-tracing-platform", "payment-system"],
  remember: "Trace the boundaries where work and ownership move. Propagate safe context deliberately, then use aggregate signals to decide whether one trace represents a systemic problem.",
}} />; }

export function RequestIdsLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "request-ids",
  mentalModel: "A request ID identifies one ingress attempt for search and support. A trace ID correlates a distributed operation. Neither authorizes access, proves identity, or replaces an idempotency key that protects a business effect.",
  mechanism: ["Accept an external correlation value only after length and character validation, or replace it at the edge.", "Generate an internal request or trace identifier and propagate it through logs and downstream calls.", "Create a separate stable idempotency key for retry-safe mutations.", "Return a safe support identifier to the caller without exposing topology or credentials.", "Index the identifier where operators can follow the request under least-privilege access."],
  example: { title: "A client retries an order creation", body: "Both HTTP attempts have different request IDs, may share one trace or linked traces, and carry the same idempotency key. The idempotency record returns the first committed order; request IDs let operators inspect both attempts.", consequence: "Model diagnostic correlation and business deduplication as separate identities with separate retention." },
  tradeoffs: [{ option: "Client-supplied correlation ID", chooseWhen: "Cross-organization support needs a shared reference.", cost: "It is untrusted input and can collide or carry unsafe data." }, { option: "Edge-generated ID", chooseWhen: "The platform needs a controlled unique namespace.", cost: "External systems need an explicit mapping." }, { option: "Single ID for every purpose", chooseWhen: "Never; the semantics differ.", cost: "Conflates observability, authentication, and business correctness." }],
  failure: { failure: "A service treats a caller-provided request ID as an authorization or dedupe key.", impact: "An attacker can collide with another request or suppress a legitimate operation.", detection: "Security tests show outcomes change when only the diagnostic header is reused.", mitigation: "Separate trusted identity, authorization, idempotency, and diagnostic identifiers; validate each at its boundary.", tradeoff: "More identifiers require clearer schemas and support tooling." },
  exercise: ["Label request ID, trace ID, session ID, user ID, and idempotency key in one write flow.", "For each, state who creates it, who trusts it, how long it lives, and what decision it may influence.", "Reject any design where a diagnostic identifier grants access."],
  probes: ["Can a client choose this ID?", "What happens across retries and asynchronous work?", "Which identifier appears in a support response?", "How do you prevent correlation fields from leaking tenant data?"],
  practice: ["api-gateway-system", "payment-system"],
  remember: "Use request and trace IDs for diagnosis, idempotency keys for repeated effects, and authenticated identity plus authorization for access. Similar-looking strings do not share semantics.",
}} />; }
