import { ProductionEngineeringLesson } from "./shared";

const tlsFlow = `sequenceDiagram
  participant C as Client
  participant E as Trusted TLS endpoint
  participant S as Application service
  C->>E: ClientHello and supported parameters
  E-->>C: ServerHello and certificate proof
  C->>E: encrypted authenticated request
  E->>S: protected internal hop
  S-->>E: response
  E-->>C: encrypted response`;

const abuseFlow = `flowchart LR
  C[Client traffic] --> E[Edge validation]
  E --> I[Identity and quota]
  I --> A[Application authorization]
  A --> Q[Bounded work queue]
  Q --> D[(Protected dependency)]
  E --> O[Abuse telemetry]
  I --> O
  A --> O`;

export function TlsLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "tls",
  mentalModel: "TLS protects a transport connection by authenticating an endpoint and deriving keys for confidentiality and integrity. It protects the hops where it is used; termination creates a new trust boundary and does not automatically protect data before encryption or after decryption.",
  mechanism: ["The client proposes supported protocol parameters and fresh key-exchange material.", "The server selects parameters and proves the configured identity through its certificate and handshake.", "Both sides derive traffic keys and verify the handshake before application data is accepted.", "The trusted termination point applies routing and policy, then establishes a separately protected internal hop where required.", "Certificate issuance, hostname validation, expiry, rotation, and failure are monitored as operational dependencies."],
  diagram: { chart: tlsFlow, title: "TLS termination creates an explicit trust boundary", description: "A client authenticates a TLS endpoint before sending encrypted application data. After termination, the platform starts a separately protected internal connection to the application service, making both hops and the plaintext boundary explicit." },
  example: { title: "Terminate at an edge proxy without assuming the network is trusted", body: "The public certificate authenticates the edge hostname. The edge decrypts the request to apply policy, then uses an authenticated encrypted connection to the service. Logs and traces omit credentials at both points.", consequence: "Treat the edge as a privileged plaintext boundary and separately define internal identity, encryption, and certificate rotation." },
  tradeoffs: [{ option: "Edge termination", chooseWhen: "Central routing, certificate operations, and protection are required.", cost: "The edge becomes a sensitive trust boundary and internal hops need explicit protection." }, { option: "End-to-service TLS", chooseWhen: "The application must authenticate the final endpoint directly.", cost: "Certificate and routing operations spread across services." }, { option: "Mutual TLS", chooseWhen: "Both endpoints need transport-level workload identity.", cost: "Issuance, rotation, revocation, and authorization remain operational work." }],
  failure: { failure: "A certificate expires during normal traffic.", impact: "Clients reject new connections even though application instances are healthy.", detection: "Expiry horizon, handshake failure, and synthetic connection checks alert before and during impact.", mitigation: "Automate renewal with overlapping deployment, monitor the served certificate, and retain a tested rollback path.", tradeoff: "Automation and fallback credentials increase the importance of protecting the issuance system." },
  exercise: ["Draw every plaintext and encrypted segment from client to datastore.", "For each TLS endpoint, name the expected identity, certificate issuer, rotation owner, and failure behavior.", "Explain what TLS does not protect after termination."],
  probes: ["Where is TLS terminated?", "Who can observe plaintext there?", "How do services authenticate internal peers?", "What happens during certificate rotation or revocation?"],
  practice: ["api-gateway-system", "webhook-delivery"],
  remember: "TLS secures a defined connection. Make endpoint identity, termination, plaintext exposure, internal hops, and certificate operations visible in the design.",
}} />; }

export function EncryptionLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "encryption",
  mentalModel: "Encryption in transit protects data between endpoints; encryption at rest protects stored media or objects. Neither substitutes for authorization, integrity-aware protocols, key isolation, field minimization, or application-layer controls while data is in use.",
  mechanism: ["Classify the data, threat, lifetime, and locations where plaintext must exist.", "Use an authenticated transport protocol for each untrusted hop.", "Encrypt storage with keys separated from the ciphertext and identities constrained to needed operations.", "For especially sensitive fields, consider application-layer encryption with explicit search and rotation limits.", "Version algorithms and keys, rotate through a tested migration, and audit decrypt operations."],
  example: { title: "Encrypt customer exports without making every service a decryptor", body: "The export worker writes an encrypted object using a scoped key operation. The download service authorizes the user and returns short-lived access; analytics jobs cannot decrypt the export merely because they can list object metadata.", consequence: "Separate storage access from key use and design the plaintext boundary around the smallest necessary worker set." },
  tradeoffs: [{ option: "Storage-layer encryption", chooseWhen: "Protect disks, snapshots, and object media with broad compatibility.", cost: "The storage service or host can still see plaintext during authorized use." }, { option: "Application-field encryption", chooseWhen: "A sensitive field must remain opaque to shared storage operators.", cost: "Search, indexing, rotation, and application key access become harder." }, { option: "One shared key", chooseWhen: "Avoid for mixed tenants and data classes.", cost: "One compromise has a large blast radius and rotation is disruptive." }],
  failure: { failure: "Ciphertext and its only decryption key are backed up together without recovery testing.", impact: "A compromise exposes both, or key loss makes the backup permanently unreadable.", detection: "Recovery exercises cannot restore with independently controlled key material.", mitigation: "Separate key controls, protect recovery material, version envelopes, and test restore plus rotation.", tradeoff: "Independent key recovery adds governance and emergency-access procedures." },
  exercise: ["Mark plaintext, ciphertext, key, and identity at each system boundary.", "Compare at-rest, transport, and application-layer encryption for one sensitive field.", "Design rotation so old and new data remain readable during migration without an all-powerful permanent key."],
  probes: ["Which threat does this encryption address?", "Where is plaintext still visible?", "Who can invoke decrypt and how is that audited?", "How do backup restore and key rotation interact?"],
  practice: ["cloud-file-storage", "payment-system"],
  remember: "Encryption protects data only against named threats at named boundaries. Minimize plaintext and key authority, then test rotation and recovery.",
}} />; }

export function SecretsManagementLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "secrets-management",
  mentalModel: "A secret is high-impact credential material such as an API key, private key, or password. Manage its creation, scoped delivery, use, rotation, revocation, and audit as one lifecycle; a secure vault does not help if applications copy values into code, logs, images, or support tools.",
  mechanism: ["Inventory secret consumers and replace shared human credentials with workload identity where possible.", "Generate high-entropy material in an approved system and assign least-privilege policy.", "Deliver at runtime over an authenticated channel; keep it out of source, build arguments, images, URLs, and telemetry.", "Rotate with overlap or versioning so producers and consumers move without outage.", "Revoke, audit use, scan for accidental copies, and rehearse compromise recovery."],
  example: { title: "Rotate a database credential without stopping writes", body: "Create a second scoped credential, update workloads to prefer it, verify old-credential use falls to zero, then revoke the first. Connection pools and long-running jobs are included in the observation window.", consequence: "Support overlapping versions and usage telemetry; rotation is a distributed rollout rather than one value replacement." },
  tradeoffs: [{ option: "Dynamic short-lived credential", chooseWhen: "The platform can authenticate workloads and issue scoped access.", cost: "The issuer becomes a runtime dependency and renewal must be reliable." }, { option: "Static managed secret", chooseWhen: "An external system cannot support workload identity.", cost: "Rotation, copying, and compromise duration require tighter operations." }, { option: "Shared secret", chooseWhen: "Avoid when per-workload identity is available.", cost: "Attribution and revocation have a large blast radius." }],
  failure: { failure: "A third-party key appears in an application error log.", impact: "Anyone with log access may impersonate the service until the key is revoked.", detection: "Secret scanning and unusual provider usage identify the value and affected scope.", mitigation: "Revoke first, issue a replacement through the managed path, restrict affected logs, and fix redaction at the source.", tradeoff: "Emergency revocation may interrupt dependent work while credentials roll." },
  exercise: ["Map generation, storage, delivery, memory use, logging, rotation, revocation, and deletion for one credential.", "Name every consumer and reduce its permissions to the required operations.", "Write the first three steps after suspected exposure; do not begin with investigation that leaves the key active."],
  probes: ["Can workload identity remove this secret?", "How does rotation avoid downtime?", "Where can the value be copied accidentally?", "What is the blast radius and revocation time?"],
  levelCalibration: [{ level: "SDE I–II", evidence: "Keep credentials out of source and logs; consume the managed runtime path." }, { level: "Senior", evidence: "Design scoped identity, rotation, revocation, and recovery for a service." }, { level: "Staff", evidence: "Reduce organization-wide secret inventory and define ownership, audit, cost, and incident policy for the platform." }],
  practice: ["cicd-platform", "api-gateway-system"],
  remember: "A secret manager is one component of a credential lifecycle. Reduce the number of secrets, scope every consumer, and make rotation and revocation routine.",
}} />; }

export function ApiAbuseDdosLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "api-abuse-ddos",
  mentalModel: "Abuse control protects scarce product and infrastructure resources from actors using valid or invalid requests at harmful scale. Begin with assets, actors, attack paths, amplification, and acceptable false positives; then layer cheap controls before expensive work.",
  mechanism: ["Threat model the endpoint: asset, attacker capability, identity, costly operation, and downstream blast radius.", "Reject malformed traffic and impossible requests at the earliest trusted edge.", "Apply identity-aware quotas, rate limits, authorization, payload bounds, and concurrency limits before expensive dependencies.", "Queue or shed bounded optional work and isolate critical traffic from noisy tenants.", "Measure blocked and allowed outcomes, investigate evasion, provide recovery or appeal where product policy requires it, and review defense cost."],
  diagram: { chart: abuseFlow, title: "Layer abuse controls before scarce work", description: "Client traffic passes through edge validation, identity and quota checks, application authorization, and a bounded work queue before reaching a protected dependency. Each layer emits abuse telemetry so operators can distinguish blocked traffic from user-visible failures." },
  example: { title: "An image endpoint triggers expensive resizing", body: "Validate dimensions and format at the edge, authorize object access, cap bytes and concurrent transforms per tenant, cache safe derivatives, and bound the worker queue. A global requests-per-second limit alone misses cost differences.", consequence: "Price or limit work by the resource it consumes and isolate the transformation fleet from unrelated critical requests." },
  tradeoffs: [{ option: "Fail closed", chooseWhen: "The protected action has financial, privacy, or irreversible impact.", cost: "Limiter or policy failure can block legitimate users." }, { option: "Fail open with caps", chooseWhen: "Availability is critical and downstream capacity remains protected.", cost: "Attack traffic may pass during control-plane failure." }, { option: "Challenge or progressive friction", chooseWhen: "Risk is uncertain and false positives are costly.", cost: "Adds user friction, accessibility work, and new bypass surfaces." }],
  failure: { failure: "The central rate-limit store becomes unavailable during an attack.", impact: "Fail-open overloads dependencies; fail-closed turns the limiter outage into a full product outage.", detection: "Limiter latency/errors rise while edge demand and downstream saturation diverge.", mitigation: "Use bounded local fallback, reserve capacity for critical identities, shed expensive optional work, and define endpoint-specific failure policy.", tradeoff: "Distributed fallback is less globally precise and can allow a bounded excess." },
  exercise: ["Choose one endpoint and rank attack paths by cost amplification, data exposure, and reversibility.", "Place one cheap validation, one identity quota, one authorization check, and one capacity protection before the scarce dependency.", "State fail-open/closed behavior and a safe recovery path for false positives."],
  probes: ["What resource is the attacker trying to exhaust or abuse?", "Which control runs before expensive parsing or storage?", "How do anonymous, authenticated, and internal callers differ?", "What happens when the defense itself is unavailable?"],
  practice: ["rate-limiter", "api-gateway-system", "webhook-delivery"],
  remember: "Threat model the scarce resource, layer controls from cheapest to most contextual, and define failure behavior for both attack traffic and the defense system.",
  note: "Do not log raw credentials, full request bodies, or attacker-supplied identifiers as metric labels. Abuse telemetry needs the same privacy, retention, and access design as other production data.",
}} />; }

export function TenantAuthorizationLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "tenant-authorization",
  mentalModel: "Multi-tenant authorization preserves a boundary between customers even when compute, caches, queues, indexes, and operations are shared. Tenant context must come from trusted membership and authoritative resource state, then follow every read, write, event, cache key, export, and support action.",
  mechanism: ["Authenticate the principal and resolve current tenant memberships from a trusted source.", "Load the resource and derive its tenant server-side before returning fields or applying mutation.", "Enforce tenant plus action policy in the service and at storage/query boundaries where possible.", "Partition cache keys, queue messages, search filters, object paths, telemetry access, and background jobs by trusted tenant context.", "Audit cross-tenant administrative access, membership changes, exports, and deletion with explicit ownership."],
  example: { title: "A report worker processes queued tenant exports", body: "The message carries an immutable job ID, not trusted free-form tenant scope. The worker loads the owner-scoped job, obtains a constrained service identity, queries with tenant predicates, encrypts the output, and records the authorized requester.", consequence: "Reconstruct authority from persisted owner state at asynchronous boundaries instead of trusting message attributes alone." },
  tradeoffs: [{ option: "Shared tables with tenant key", chooseWhen: "Scale and operations favor shared storage with strong query enforcement.", cost: "Every query, index, cache, and migration must preserve the tenant predicate." }, { option: "Schema or database per tenant", chooseWhen: "Isolation or compliance outweighs fleet complexity.", cost: "Provisioning, migrations, pooling, and cross-tenant operations become expensive." }, { option: "Support impersonation", chooseWhen: "Only with explicit product need and controlled approval.", cost: "It creates a privileged cross-tenant path requiring strong audit and expiry." }],
  failure: { failure: "A cache key uses object ID without tenant ID.", impact: "The same identifier in two tenants can return one tenant's data to another.", detection: "Cross-tenant tests alternate identical object IDs and observe cache contamination.", mitigation: "Include trusted tenant and authorization-relevant version in keys, and reauthorize sensitive results after cache lookup.", tradeoff: "More specific keys reduce cache sharing and hit rate." },
  exercise: ["Trace tenant context through API, database, cache, queue, object storage, search, logs, and support tooling.", "Write negative tests for same-ID cross-tenant reads, writes, exports, and cached responses.", "Name the owner and expiry of every administrative bypass."],
  probes: ["Where does tenant context originate?", "Can a background worker exceed the initiating user's authority?", "How do cache and search indexes preserve isolation?", "How are support access and deletion proven?"],
  levelCalibration: [{ level: "SDE I–II", evidence: "Apply server-derived tenant predicates and negative tests to every endpoint." }, { level: "Senior", evidence: "Carry isolation through caches, jobs, storage, search, exports, and migrations." }, { level: "Staff", evidence: "Choose an isolation model, define privileged operations, and make privacy, reliability, and cost trade-offs explicit." }],
  practice: ["cloud-file-storage", "ecommerce", "metrics-platform"],
  remember: "Tenant isolation is an end-to-end invariant, not one database column. Derive context from trusted state and preserve it across every synchronous, asynchronous, cached, and operational path.",
}} />; }
