import { ProductionEngineeringLesson } from "./shared";

export function AlertsLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "alerts",
  mentalModel: "An alert is a request for timely human action. Page on a user-visible symptom or imminent exhaustion with a documented response; use tickets and dashboards for conditions that do not require interruption.",
  mechanism: ["Choose the service-level symptom and the urgency of the required response.", "Measure the condition over windows that reject short noise but detect harmful burn quickly.", "Route to the owning team with severity, affected scope, links, and a tested runbook.", "Deduplicate related notifications and define escalation when acknowledgement or mitigation does not occur.", "Review pages for actionability, false positives, missed incidents, and operator load."],
  example: { title: "Page on fast error-budget burn", body: "A checkout service pages when failures are consuming the monthly error budget at a rate that will exhaust it quickly, confirmed over both a short and longer window. One transient error spike does not page.", consequence: "Tie paging urgency to user harm and budget burn rather than a raw CPU threshold." },
  tradeoffs: [{ option: "Symptom alert", chooseWhen: "Users are affected or an SLO is at risk.", cost: "Diagnosis begins after the alert and requires linked evidence." }, { option: "Cause alert", chooseWhen: "A resource condition reliably predicts imminent harm and has one owner action.", cost: "Infrastructure thresholds often create noise without user impact." }, { option: "Ticket", chooseWhen: "Action is needed but not immediately.", cost: "The condition may wait until business hours." }],
  failure: { failure: "Every instance pages independently during a regional dependency outage.", impact: "Operators receive hundreds of notifications and cannot see the common symptom.", detection: "Alert volume and shared dependency errors spike across services at once.", mitigation: "Aggregate by service and region, inhibit derivative pages, and preserve one incident with linked affected components.", tradeoff: "Aggressive grouping can hide a distinct simultaneous failure." },
  exercise: ["Classify five candidate conditions as page, ticket, dashboard, or discard.", "For each page, name the user symptom, response deadline, owner action, and stop condition.", "Write a runbook first step that can be completed without guessing dashboard names."],
  probes: ["What action should the page recipient take now?", "Why is this threshold tied to user harm?", "How do you detect both fast and slow burns?", "What inhibits downstream alert storms?"],
  practice: ["metrics-platform", "log-aggregation"],
  remember: "Page only when a person must act now. Anchor the signal in user harm, route it to an owner, and make the first diagnostic step explicit.",
}} />; }

export function SlisLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "slis",
  mentalModel: "A service level indicator is a measured ratio or distribution representing what users experience. Define its population, good-event rule, measurement point, exclusions, and known bias before assigning a target.",
  mechanism: ["Name the user journey and count the total eligible events.", "Define which events are good: successful, fast enough, fresh enough, or correct enough.", "Choose a measurement point close to the user while retaining diagnostic dimensions separately.", "Record exclusions such as invalid requests explicitly rather than silently deleting hard cases.", "Validate the indicator against real incidents and gaps in instrumentation."],
  example: { title: "Checkout availability SLI", body: "Total events are valid checkout confirmations at the edge. Good events return the documented success outcome within 1.5 seconds. Client validation failures are excluded; authenticated server failures and timeouts are not.", consequence: "Measure the complete user-facing path at the boundary, then use internal metrics to diagnose which dependency caused a bad event." },
  tradeoffs: [{ option: "Edge measurement", chooseWhen: "End-to-end user experience matters.", cost: "It may not reveal the failing internal component." }, { option: "Server handler measurement", chooseWhen: "The service owns a well-defined internal contract.", cost: "It omits network, proxy, and client-side failures." }, { option: "Synthetic probe", chooseWhen: "Real traffic is sparse or continuous coverage is required.", cost: "The probe may not match actual users or data." }],
  failure: { failure: "The SLI counts only requests that reached a healthy application instance.", impact: "Load-balancer, routing, and startup failures disappear from availability reporting.", detection: "Edge errors rise while the application-reported SLI remains healthy.", mitigation: "Measure at the externally meaningful boundary and reconcile edge totals with application telemetry.", tradeoff: "Boundary measurement includes failures outside the team's direct control but inside the user journey." },
  exercise: ["Write numerator, denominator, threshold, and measurement point for one journey.", "List excluded events and defend each exclusion.", "Name one instrumentation failure that would make the indicator look healthier than users are."],
  probes: ["What exactly is a total event?", "Where is the indicator measured?", "Does the metric include timeouts and dropped traffic?", "How would you measure correctness or freshness, not only availability?"],
  practice: ["metrics-platform", "payment-system"],
  remember: "An SLI is only credible when its event population, good-event rule, measurement boundary, and bias are explicit.",
}} />; }

export function SlosLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "slos",
  mentalModel: "A service level objective is a target for an SLI over a time window. It expresses the reliability needed for a user journey and creates room for imperfection; it is not automatically a contractual SLA or a promise of zero failure.",
  mechanism: ["Select a user-centered SLI and a window long enough to guide decisions.", "Choose a target from product need, dependency capability, recovery time, and the cost of higher reliability.", "Define how the window moves, how delayed data is handled, and which traffic classes are separate.", "Use budget consumption to prioritize release, reliability, and capacity work.", "Revisit a target when user behavior, architecture, or business criticality changes."],
  example: { title: "Why 99.99% is a design decision", body: "For 30 days, 99.9% permits roughly 43 minutes of bad time if measured by time, while 99.99% permits roughly 4 minutes. A dependency with longer failover cannot support the tighter target without architectural change.", consequence: "Agree on the target before promising multi-region failover, extra replicas, or operational staffing whose cost may not serve the product." },
  tradeoffs: [{ option: "Tighter objective", chooseWhen: "Small outages create material user or business harm.", cost: "Redundancy, testing, operational coverage, and slower change cost more." }, { option: "Separate journey objectives", chooseWhen: "Read, write, and administrative paths have different criticality.", cost: "More indicators and policies must remain understandable." }, { option: "One service-wide objective", chooseWhen: "The service is simple and user paths share failure behavior.", cost: "A healthy aggregate can hide one critical journey." }],
  failure: { failure: "A team sets a 100% objective and treats every error as an emergency.", impact: "Risky work is hidden, releases stall, and operators chase failures the architecture cannot economically eliminate.", detection: "Budget is always zero and policy cannot distinguish harmful regression from expected imperfection.", mitigation: "Choose a product-backed target below perfection and document the budget response.", tradeoff: "The product explicitly accepts a bounded amount of failure." },
  exercise: ["Choose one SLI and compare the operational consequence of two targets.", "List the dependencies and recovery time that constrain the target.", "Define separate objectives only where user impact or ownership truly differs."],
  probes: ["Why this target and window?", "What architecture would a tighter objective require?", "How do low-traffic services avoid misleading windows?", "How does this objective influence release decisions?"],
  levelCalibration: [{ level: "SDE I–II", evidence: "Define a user-centered SLI and explain the target window." }, { level: "Senior", evidence: "Connect dependency budgets, failure recovery, and alerting to the objective." }, { level: "Staff", evidence: "Negotiate objectives across product and platform boundaries and make the reliability cost visible." }],
  practice: ["metrics-platform", "payment-system"],
  remember: "Choose an SLO from user need and achievable system behavior. A tighter number is not maturity unless the product value justifies its engineering and operational cost.",
}} />; }

export function ErrorBudgetsLessonContent() { return <ProductionEngineeringLesson spec={{
  id: "error-budgets",
  mentalModel: "An error budget is the amount of bad service allowed by an SLO. Budget policy converts that remaining tolerance and its rate of consumption into explicit decisions about release pace, risk, and reliability work.",
  mechanism: ["Calculate good and total events using the agreed SLI and window.", "Translate the SLO target into allowable bad events, then track remaining budget and burn rate.", "Define policy before exhaustion: who decides, which changes pause, and which reliability work takes priority.", "Use multiple windows to distinguish sudden incidents from a slow regression.", "Reset or revise policy only through the agreed product and engineering process, not to erase failure."],
  example: { title: "A small failure rate burns quickly at high traffic", body: "At 10 million eligible requests, a 99.9% objective allows 10,000 bad requests. A release causing 5,000 additional bad requests has spent half the window's budget even if dashboards still show 99.95% success.", consequence: "Measure budget consumption and release impact, not only whether the current percentage is above a dashboard line." },
  tradeoffs: [{ option: "Freeze risky releases", chooseWhen: "Budget is exhausted and changes are likely to worsen user harm.", cost: "Feature delivery slows while reliability recovers." }, { option: "Continue reliability changes", chooseWhen: "A tested fix or protective control reduces burn.", cost: "Any production change can introduce new failure." }, { option: "Different budgets by journey", chooseWhen: "Criticality and ownership differ materially.", cost: "Policy becomes harder to coordinate and explain." }],
  failure: { failure: "The team resets the window after a bad release to make the budget green.", impact: "The signal stops constraining risk and users absorb repeated unreliability.", detection: "Window definitions or exclusions change immediately after exhaustion without a product decision.", mitigation: "Keep window and policy versioned, record exceptions, and require accountable approval for target changes.", tradeoff: "Governance slows ad hoc decisions during delivery pressure." },
  exercise: ["For 2,000,000 events and a 99.95% target, calculate allowed bad events.", "Write the policy at 25%, 75%, and 100% budget consumption.", "Name one reliability change allowed during a release pause and the evidence needed to ship it."],
  probes: ["How fast is the budget burning?", "Which changes stop when it is exhausted?", "Who can approve an exception?", "How do you prevent a high-volume endpoint from hiding a critical low-volume journey?"],
  practice: ["metrics-platform", "cicd-platform"],
  remember: "An error budget is useful only when its calculation is stable and its policy changes real decisions before and after exhaustion.",
}} />; }
