import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { notFound } from "next/navigation";
import { AccountUnavailable } from "@/components/account-unavailable";
import { RevisionConfirmAction } from "@/features/applications/revision-confirm-action";
import { deleteStoryAction, duplicateStoryAction, linkQuestionToStoryAction } from "@/features/behavioral/actions";
import { isAccountPlatformAvailable } from "@/lib/account-platform";
import { requireMemberProfile } from "@/lib/auth/guards";
import { getBehavioralWorkspaceData } from "@/lib/behavioral/queries";
import { storyReadiness } from "@/lib/behavioral/readiness";
export const metadata: Metadata = { title: "Behavioral story", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

export default async function BehavioralStoryPage({ params }: { params: Promise<{ id: string }> }) {
  if (!isAccountPlatformAvailable()) return <AccountUnavailable />; const { id } = await params; await requireMemberProfile(`/behavioral/stories/${id}`); const data = await getBehavioralWorkspaceData(); const story = data.stories.find((item) => item.id === id); if (!story) notFound(); const themes = data.themes.filter((theme) => theme.story_id === id); const links = data.links.filter((link) => link.story_id === id); const answers = data.answers.filter((answer) => answer.story_id === id);
  const linkedQuestions = links.map((link) => data.questions.find((question) => link.curated_question_id === question.id || link.custom_question_id === question.id)).filter(Boolean); const availableQuestions = data.questions.filter((question) => !linkedQuestions.some((linked) => linked?.id === question.id)); const readiness = storyReadiness(story);
  return <div className="behavioral-workspace"><div className="page-width behavioral-detail-width"><Link className="behavioral-back" href="/behavioral/stories"><ArrowLeft size={14} />Story bank</Link><header className="behavioral-detail-header"><div className="behavioral-card-meta"><span>{readiness === "Ready" ? "Content complete" : readiness}</span>{story.company_or_context && <span>{story.company_or_context}</span>}{story.role && <span>{story.role}</span>}{story.approximate_period && <span>{story.approximate_period}</span>}</div><h1>{story.title}</h1>{story.short_summary && <p>{story.short_summary}</p>}<div className="behavioral-theme-tags">{themes.map((theme) => <span key={theme.id}>{theme.theme}</span>)}</div><p className="behavioral-readiness-note">Content completeness reflects only visible STAR detail: context, responsibility, personal action, and outcome. It does not predict interview performance.</p><div className="behavioral-detail-actions"><Link className="button button-sm" href={`/behavioral/stories/${id}/edit`}>Edit source facts</Link><form action={duplicateStoryAction.bind(null, id)}><button className="button button-secondary button-sm">Duplicate</button></form><RevisionConfirmAction action={deleteStoryAction.bind(null, story.id, story.updated_at)} label="Delete story" latestHref={`/behavioral/stories/${story.id}`} /></div></header>
    <section className="behavioral-star-display">{([ ["Situation", story.situation], ["Task", story.task], ["Action", story.action], ["Result", story.result], ["Reflection", story.reflection] ] as const).map(([label, value]) => <article key={label}><span>{label}</span><p>{value || "Not written yet."}</p></article>)}</section>
    <section className="behavioral-detail-section"><div className="behavioral-section-heading"><div><h2>Linked questions</h2><p>{linkedQuestions.length} question{linkedQuestions.length === 1 ? "" : "s"} can use this story. Categories show where this evidence is reusable.</p></div>{availableQuestions.length ? <form action={linkQuestionToStoryAction.bind(null, id)} className="behavioral-inline-form"><label className="sr-only" htmlFor="story-link-question">Question to link</label><select id="story-link-question" name="question_id" required defaultValue=""><option value="" disabled>Choose a question</option>{availableQuestions.map((question) => <option key={question.id} value={question.id}>{question.prompt}</option>)}</select><button className="button button-secondary button-sm">Link question</button></form> : <Link className="button button-secondary button-sm" href="/behavioral/questions">Browse questions</Link>}</div>{linkedQuestions.length ? <div className="behavioral-linked-list">{linkedQuestions.map((question) => question && <article key={question.id}><div><Link href={`/behavioral/questions/${question.id}`}>{question.prompt}</Link><span>{question.category}</span></div><Link href={`/behavioral/questions/${question.id}/answers/new?story=${id}`}>Create variant</Link></article>)}</div> : <p className="behavioral-empty-inline">This story is not linked yet. Link it to every prompt it can credibly answer.</p>}</section>
    <section className="behavioral-detail-section"><div className="behavioral-section-heading"><div><h2>Question-specific preparation</h2></div></div>{answers.length ? <div className="behavioral-answer-list">{answers.map((answer) => { const application = data.applications.find((item) => item.id === answer.application_id); return <article key={answer.id}><header><div><h3>{answer.title}{answer.is_primary && <span className="behavioral-primary-label">Primary</span>}</h3><span>{answer.status}{application ? ` · ${application.company_name}` : answer.company_slug ? ` · ${answer.company_slug.replaceAll("-", " ")}` : " · General"}</span></div></header>{answer.opening_framing && <p><strong>Opening:</strong> {answer.opening_framing}</p>}{answer.details_to_emphasize && <p><strong>Emphasize:</strong> {answer.details_to_emphasize}</p>}{answer.answer_text && <p>{answer.answer_text}</p>}</article>; })}</div> : <p className="behavioral-empty-inline">No question-specific preparation references this story yet.</p>}</section>
    {story.notes && <section className="behavioral-private-notes"><span>Private notes</span><p>{story.notes}</p></section>}
  </div></div>;
}
