"use client";

import { Github, Mail } from "lucide-react";
import { track } from "@/lib/analytics";

export function SignInPanel() {
  const configured = Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
  function begin(method: string) { track("account_signup_started", { method }); }
  return <div className="form-shell" style={{ maxWidth:460, margin:"0 auto" }}><div className="feature-card-top"><span className="logo-mark"><span>EF</span></span><span className="demo-label">{configured ? "Supabase ready" : "Setup required"}</span></div><h2 style={{ fontSize:28,letterSpacing:"-.04em",margin:"28px 0 8px" }}>Welcome to the Foundry.</h2><p className="muted" style={{ fontSize:13,lineHeight:1.6,marginBottom:22 }}>Sign in will unlock saved progress, practice, referrals, challenges, and your profile.</p><div style={{ display:"grid",gap:9 }}><button className="button button-secondary" type="button" onClick={() => begin("google")}><span style={{ fontWeight:900 }}>G</span> Continue with Google</button><button className="button button-secondary" type="button" onClick={() => begin("github")}><Github size={16} /> Continue with GitHub</button></div><div style={{ display:"flex",alignItems:"center",gap:10,margin:"20px 0",color:"var(--muted)",fontSize:10 }}><span style={{ height:1,background:"var(--line)",flex:1 }} />OR<span style={{ height:1,background:"var(--line)",flex:1 }} /></div><form onSubmit={(event) => { event.preventDefault(); begin("email"); }}><div className="form-group"><label htmlFor="auth-email">Email address</label><input id="auth-email" type="email" required placeholder="you@example.com" /></div><button className="button" style={{ width:"100%",marginTop:12 }} type="submit"><Mail size={16} /> Continue with email</button></form>{!configured && <div className="form-note" style={{ marginTop:20 }}>Authentication UI is in preview mode. Add the Supabase environment variables and configure OAuth providers to enable account creation.</div>}<p className="muted" style={{ fontSize:10.5,lineHeight:1.5,margin:"18px 0 0",textAlign:"center" }}>By continuing, you agree to the Terms and acknowledge the Privacy Policy.</p></div>;
}
