import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, LockKeyhole, MessageSquareQuote } from "lucide-react";
import { behavioralLearningSources, behavioralLessonHref, behavioralLessonPhases, behavioralLessons } from "@/data/behavioral/lessons";

export function BehavioralLearningPath() {
  return <div className="behavioral-learn" data-impeccable-seed="f31e86c0">
    <header className="behavioral-learn-hero"><div className="page-width"><nav aria-label="Breadcrumb"><Link href="/behavioral">Behavioral</Link><span>/</span><span>Learn</span></nav><span>Evidence preparation · 16 lessons</span><h1>Build answers that survive the next question.</h1><p>Learn to preserve facts, expose judgment, handle follow-ups, and calibrate scope without turning yourself into a score.</p><div><Link className="button" href={behavioralLessonHref(behavioralLessons[0].slug)}>Start lesson 01 <ArrowRight size={15} /></Link><Link className="button button-secondary" href="/behavioral#explorer">Browse 48 prompts</Link></div></div></header>
    <div className="page-width behavioral-learn-body">
      <section className="behavioral-learn-contract" aria-label="Learning path contract"><div><BookOpen size={17} aria-hidden="true" /><p><strong>One evidence system</strong><span>Lessons, the existing question catalog, and private story workspace use the same truth and privacy boundaries.</span></p></div><div><LockKeyhole size={17} aria-hidden="true" /><p><strong>No private content here</strong><span>The public path contains examples and exercises only. Your story and answer text belongs in your private workspace or a tool you control.</span></p></div><div><MessageSquareQuote size={17} aria-hidden="true" /><p><strong>No hiring prediction</strong><span>Completion means you reviewed material. It never means readiness, personality fit, or likely interview outcome.</span></p></div></section>

      <section className="behavioral-learn-sequence" aria-labelledby="behavioral-sequence-heading"><header><span>Curriculum map</span><h2 id="behavioral-sequence-heading">Four passes from source facts to live follow-up.</h2><p>Each lesson ends in a concrete action. Follow the sequence once, then return only to the evidence gap you need.</p></header>{behavioralLessonPhases.map((phase) => {
        const lessons = behavioralLessons.filter((lesson) => lesson.phase === phase.id);
        return <section className="behavioral-learn-phase" key={phase.id}><header><span>{phase.label}</span><p>{phase.description}</p></header><ol>{lessons.map((lesson) => <li key={lesson.slug}><span>{String(lesson.number).padStart(2, "0")}</span><div><small>{lesson.level} · {lesson.estimatedMinutes} min</small><h3>{lesson.title}</h3><p>{lesson.objective}</p></div><Link href={behavioralLessonHref(lesson.slug)} aria-label={`Open lesson ${lesson.number}: ${lesson.title}`}>Open <ArrowRight size={14} /></Link></li>)}</ol></section>;
      })}</section>

      <section className="behavioral-learn-handoff"><div><span>After the path</span><h2>Move from reading to evidence.</h2><p>Choose an original prompt, map it to a truthful source story, rehearse a bounded answer, then bring the observed gap back to the Interview Playbook.</p></div><ol><li><CheckCircle2 size={15} />Choose a prompt</li><li><CheckCircle2 size={15} />Select source evidence</li><li><CheckCircle2 size={15} />Rehearse and probe</li><li><CheckCircle2 size={15} />Record one next action</li></ol><nav><Link href="/behavioral/practice">Run the evidence-gap drill</Link><Link href="/behavioral/review">Open the review rubric</Link><Link href="/behavioral/workspace">Open private workspace</Link><Link href="/interview-playbook">Return to Interview Playbook</Link></nav></section>

      <details className="behavioral-learn-sources"><summary>Research and source boundary</summary><p>Reviewed September 5, 2026. These sources support structured, job-related evidence and role-relative calibration. Engineering Foundry’s lesson sequence, examples, exercises, and privacy boundaries are an original editorial synthesis—not a claim that every employer uses one process.</p><ul>{behavioralLearningSources.map((source) => <li key={source.id}><a href={source.url} target="_blank" rel="noopener noreferrer"><strong>{source.label}</strong><span>{source.publisher}</span></a><p>{source.supports}</p></li>)}</ul></details>
    </div>
  </div>;
}
