import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, ExternalLink, LockKeyhole } from "lucide-react";
import { behavioralLearningSources, behavioralLessonHref, behavioralLessons, type BehavioralLesson } from "@/data/behavioral/lessons";

export function BehavioralLessonPage({ lesson }: { lesson: BehavioralLesson }) {
  const previous = behavioralLessons[lesson.number - 2];
  const next = behavioralLessons[lesson.number];
  const sources = lesson.sourceIds.map((id) => behavioralLearningSources.find((source) => source.id === id)).filter((source): source is NonNullable<typeof source> => Boolean(source));
  return <div className="behavioral-lesson-page" data-impeccable-seed="f31e86c0"><div className="page-width">
    <nav className="behavioral-lesson-breadcrumb" aria-label="Breadcrumb"><Link href="/behavioral/learn"><ArrowLeft size={14} />Behavioral learning path</Link><span>/</span><span>Lesson {String(lesson.number).padStart(2, "0")}</span></nav>
    <div className="behavioral-lesson-layout"><article>
      <header className="behavioral-lesson-header"><span>{lesson.phase} · {lesson.level} · {lesson.estimatedMinutes} min</span><h1>{lesson.title}</h1><p>{lesson.objective}</p><aside><strong>Working takeaway</strong><span>{lesson.takeaway}</span></aside></header>
      <section className="behavioral-lesson-concepts" aria-label="Lesson concepts">{lesson.concepts.map((concept, index) => <section key={concept.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{concept.title}</h2><p>{concept.body}</p><ul>{concept.checks.map((check) => <li key={check}><Check size={14} aria-hidden="true" />{check}</li>)}</ul></div></section>)}</section>
      <section className="behavioral-lesson-example" aria-labelledby="worked-example-heading"><header><span>Worked evidence comparison</span><h2 id="worked-example-heading">{lesson.example.title}</h2><p>{lesson.example.context}</p></header><div><article><small>Weak or brittle</small><p>{lesson.example.weak}</p></article><article><small>Stronger evidence</small><p>{lesson.example.stronger}</p></article></div><ul>{lesson.example.annotations.map((annotation) => <li key={annotation}>{annotation}</li>)}</ul></section>
      <section className="behavioral-lesson-exercise" aria-labelledby="lesson-exercise-heading"><header><span>Practice before proceeding</span><h2 id="lesson-exercise-heading">{lesson.exercise.prompt}</h2></header><ol>{lesson.exercise.steps.map((step, index) => <li key={step}><span>{index + 1}</span>{step}</li>)}</ol><details><summary>Open the answer check</summary><p>{lesson.exercise.answerCheck}</p></details><aside><LockKeyhole size={15} aria-hidden="true" /><p>This page does not collect your response. Keep private or confidential story material in the signed-in workspace or a tool you control.</p></aside></section>
      <nav className="behavioral-lesson-next" aria-label="Lesson sequence">{previous ? <Link href={behavioralLessonHref(previous.slug)}><span>Previous</span><strong>{previous.navigationTitle}</strong></Link> : <Link href="/behavioral/learn"><span>Previous</span><strong>Curriculum map</strong></Link>} {next ? <Link href={behavioralLessonHref(next.slug)}><span>Next</span><strong>{next.navigationTitle}</strong><ArrowRight size={14} /></Link> : <Link href="/behavioral/practice"><span>Next</span><strong>Run a follow-up drill</strong><ArrowRight size={14} /></Link>}</nav>
    </article><aside className="behavioral-lesson-rail"><nav aria-label="Behavioral lesson sequence"><strong>16-lesson path</strong><ol>{behavioralLessons.map((item) => <li key={item.slug}><Link href={behavioralLessonHref(item.slug)} aria-current={item.slug === lesson.slug ? "page" : undefined}><span>{String(item.number).padStart(2, "0")}</span>{item.navigationTitle}</Link></li>)}</ol></nav><details><summary>Sources for this lesson</summary><ul>{sources.map((source) => <li key={source.id}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.label}<ExternalLink size={11} aria-hidden="true" /></a><span>{source.publisher}</span></li>)}</ul><p>Reviewed September 5, 2026. Sources support the boundary, not a universal employer process.</p></details><Link className="behavioral-lesson-playbook" href="/interview-playbook">Return to Interview Playbook <ArrowRight size={13} /></Link></aside></div>
  </div></div>;
}
