import Link from "next/link";
import { ArrowLeft, ArrowRight, ShieldCheck } from "lucide-react";
import { behavioralPracticeContexts, behavioralPracticeLevels, behavioralRubricDimensions, behavioralSelfReviewQuestions } from "@/lib/behavioral/adaptive-practice";

const bandLabels = { "needs-evidence": "Needs evidence", acceptable: "Acceptable", strong: "Strong", exceptional: "Exceptional" } as const;

export function BehavioralReviewReference() {
  return <main className="behavioral-review-reference" data-impeccable-seed="f31e86c0"><div className="page-width">
    <nav className="behavioral-drill-back" aria-label="Breadcrumb"><Link href="/behavioral"><ArrowLeft size={14} />Behavioral</Link><span>/</span><span>Review</span></nav>
    <header><div><h1>Review evidence, dimension by dimension.</h1><p>Use descriptive anchors to locate the next question—not to collapse a person or an interview into a score.</p></div><aside><ShieldCheck size={18} aria-hidden="true" /><p>Assess only observable answer evidence. Never infer honesty, personality, culture fit, accent quality, emotion, confidence, eye contact, “executive presence,” or hire probability.</p></aside></header>
    <section className="behavioral-rubric" aria-labelledby="rubric-heading"><div><h2 id="rubric-heading">Eleven evidence dimensions</h2><p>Each row stands alone. “Exceptional” is not required; the useful result is a supported observation and a next probe.</p></div><div className="behavioral-rubric-table-wrap"><table><thead><tr><th>Dimension</th>{Object.values(bandLabels).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{behavioralRubricDimensions.map((dimension) => <tr key={dimension.id}><th scope="row"><strong>{dimension.label}</strong><span>{dimension.description}</span></th>{Object.entries(dimension.bands).map(([band, text]) => <td key={band}>{text}</td>)}</tr>)}</tbody></table></div></section>
    <section className="behavioral-calibration" aria-labelledby="calibration-heading"><div><h2 id="calibration-heading">Level and context calibration</h2><p>Scope is relative. Bigger organizations and management titles are not proxies for stronger evidence.</p></div><div><section><h3>Target level</h3>{behavioralPracticeLevels.map((level) => <article key={level.id}><strong>{level.label}</strong><p>{level.guidance}</p></article>)}</section><section><h3>Context lens</h3>{behavioralPracticeContexts.filter((item) => item.id !== "general").map((context) => <article key={context.id}><strong>{context.label}</strong><p>{context.guidance}</p></article>)}</section></div></section>
    <section className="behavioral-review-order"><div><h2>Self-review comes first</h2><ol>{behavioralSelfReviewQuestions.map((item, index) => <li key={item}><span>{index + 1}</span>{item}</li>)}</ol></div><aside><h2>Then use feedback in order</h2><ol><li><strong>Candidate reflection</strong><span>Your own account of what changed.</span></li><li><strong>Observable evidence</strong><span>What the story or transcript actually contains.</span></li><li><strong>Deterministic findings</strong><span>Missing fields, consistency, length, source freshness.</span></li><li><strong>Heuristic questions</strong><span>Questions about “we,” setup length, reuse, metrics, or blame—never verdicts.</span></li><li><strong>Model-assisted observations</strong><span>Uncertain observations labeled as such, never hiring inference.</span></li><li><strong>Next actions</strong><span>One to three changes that improve the next attempt.</span></li></ol></aside></section>
    <footer className="behavioral-review-footer"><Link className="button" href="/behavioral/practice">Run an evidence-gap drill <ArrowRight size={15} /></Link><Link className="button button-secondary" href="/interview-playbook">Return to Interview Playbook</Link></footer>
  </div></main>;
}
