export const USERNAME_PATTERN = /^[a-z0-9][a-z0-9_-]{2,29}$/;

export const RESERVED_USERNAMES = [
  "admin",
  "administrator",
  "root",
  "support",
  "help",
  "staff",
  "moderator",
  "moderators",
  "mod",
  "official",
  "system",
  "security",
  "auth",
  "api",
  "engineeringfoundry",
  "engineering-foundry",
  "engineering_foundry",
  "owner",
  "team",
  "abuse",
  "contact",
  "legal",
  "privacy",
  "terms",
  "account",
  "settings",
  "dashboard",
  "signin",
  "signup",
  "login",
  "logout",
] as const;
