import { EventStreamingLessonContent, MessageQueuesLessonContent, ProducersConsumersLessonContent, PubSubLessonContent, QueueVsPubsubLessonContent, QueueVsStreamLessonContent, SyncVsAsyncLessonContent } from "./core";
import { FlinkBridgeLessonContent, KafkaConsumerGroupsOffsetsLessonContent, KafkaDeliveryGuaranteesLessonContent, KafkaFundamentalsLessonContent, KafkaPartitionsReplicationLessonContent, KafkaVsQueuesLessonContent, RabbitMqSqsLessonContent } from "./kafka";
import { BackpressureLessonContent, ChangeDataCaptureLessonContent, DeadLetterQueuesLessonContent, DeduplicationLessonContent, EventDrivenArchitectureLessonContent, EventSourcingLessonContent, TransactionalOutboxLessonContent } from "./operations";
import { ConsumerGroupsLessonContent, DeliverySemanticsLessonContent, IdempotentConsumersLessonContent, MessageOrderingLessonContent, MessageRetriesLessonContent, PartitionsLessonContent } from "./partition-delivery";

export const messagingLessonIds = new Set(["sync-vs-async", "message-queues", "producers-consumers", "queue-vs-pubsub", "pub-sub", "event-streaming", "queue-vs-stream", "partitions", "consumer-groups", "message-ordering", "delivery-semantics", "idempotent-consumers", "message-retries", "dead-letter-queues", "deduplication", "backpressure", "event-driven-architecture", "event-sourcing", "transactional-outbox", "change-data-capture", "kafka", "kafka-partitions-replication", "kafka-consumer-groups-offsets", "kafka-delivery-guarantees", "kafka-vs-queues", "rabbitmq-sqs", "flink"]);

export function MessagingLessonContent({ lessonId }: { lessonId: string }) {
  switch (lessonId) {
    case "sync-vs-async": return <SyncVsAsyncLessonContent />; case "message-queues": return <MessageQueuesLessonContent />; case "producers-consumers": return <ProducersConsumersLessonContent />; case "queue-vs-pubsub": return <QueueVsPubsubLessonContent />; case "pub-sub": return <PubSubLessonContent />; case "event-streaming": return <EventStreamingLessonContent />; case "queue-vs-stream": return <QueueVsStreamLessonContent />; case "partitions": return <PartitionsLessonContent />; case "consumer-groups": return <ConsumerGroupsLessonContent />; case "message-ordering": return <MessageOrderingLessonContent />; case "delivery-semantics": return <DeliverySemanticsLessonContent />; case "idempotent-consumers": return <IdempotentConsumersLessonContent />; case "message-retries": return <MessageRetriesLessonContent />; case "dead-letter-queues": return <DeadLetterQueuesLessonContent />; case "deduplication": return <DeduplicationLessonContent />; case "backpressure": return <BackpressureLessonContent />; case "event-driven-architecture": return <EventDrivenArchitectureLessonContent />; case "event-sourcing": return <EventSourcingLessonContent />; case "transactional-outbox": return <TransactionalOutboxLessonContent />; case "change-data-capture": return <ChangeDataCaptureLessonContent />; case "kafka": return <KafkaFundamentalsLessonContent />; case "kafka-partitions-replication": return <KafkaPartitionsReplicationLessonContent />; case "kafka-consumer-groups-offsets": return <KafkaConsumerGroupsOffsetsLessonContent />; case "kafka-delivery-guarantees": return <KafkaDeliveryGuaranteesLessonContent />; case "kafka-vs-queues": return <KafkaVsQueuesLessonContent />; case "rabbitmq-sqs": return <RabbitMqSqsLessonContent />; case "flink": return <FlinkBridgeLessonContent />; default: return null;
  }
}
